### ISSUE TITLE
Avoid using Slovak in our verification URLs

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#104]
Could be related to yesterday’s AWS blacklisting issue, but perhaps we should avoid inadvertently using Slovak in our verification URLs.
<img width="912" alt="slovak" src="https://cloud.githubusercontent.com/assets/68213/11566444/71830746-99b0-11e5-8470-92aae8cd26c4.png">

**Comment by rfk** [comment]
As in, something in all that junk in the URL parsed as valid Slovak?  Wow.

Possibly the best way to avoid this is to simply make them shorter (https://github.com/mozilla/fxa-content-server/issues/3026) at which point we could consider using a different encoding that would avoid this problem.

**Comment by ryanfeeley** [comment]
Yeah. Infinite monkey theorem at work here.

**Comment by vladikoff** [comment]
from mtg: Closing in favour of https://github.com/mozilla/fxa-content-server/issues/3026
