### ISSUE TITLE
Add a further warning to reset email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#105]
Another report of a user inadvertently wiping their sync data. We should add this line in white with red background: "This will erase any Sync data we have as it is encrypted with your password."
<img width="369" alt="reset-email" src="https://cloud.githubusercontent.com/assets/68213/11747271/3f54edd4-9ff0-11e5-9fb9-4f846f813ee7.png">
Related: https://github.com/mozilla/fxa-content-server/issues/3320

**Comment by vladikoff** [comment]
@ryanfeeley should we do this if we do the content server warning? 2 warnings??

@ryanfeeley jrgm says that the order might be wrong, the question is "Are you sure?", should the "please confirm..." follow up right away after the question. sounds like " are you sure that I want to erase all my data"

**Comment by shane-tomlinson** [comment]
> Another report of a user inadvertently wiping their sync data

The warning is ever so slightly incorrect. The servers lose the Sync data, but if the user has a local copy of the Sync data on any of their devices, it should re-upload the data to the server. @rfk am I correct with that statement?

**Comment by ryanfeeley** [comment]
Good points. And I think that I should factor in the new password page too. Assigning to myself to rework all three screens.
<img width="544" alt="screenshot 2015-12-15 11 46 16" src="https://cloud.githubusercontent.com/assets/68213/11817107/7af292fe-a321-11e5-90e4-ff90ea7b3605.png">

**Comment by rfk** [comment]
> The servers lose the Sync data, but if the user has a local copy of the Sync data
> on any of their devices, it should re-upload the data to the server

Indeed correct.

**Comment by ryanfeeley** [comment]
Replaced by reset flow copy improvement. https://github.com/mozilla/fxa/blob/rfeeley/reset-password/features/FxA-72-reset-password/README.md
