### ISSUE TITLE
Consult on improved copy for password reset flow

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#108]
Unlike typical accounts that don't encrypt the user's data with the user's password, resetting a Firefox Account wipes the Sync data from our server.

Users who are only syncing one device that they lose/break, and then reset their password when signing in on a new machine, are discovering that their Sync data (bookmarks, history, passwords, etc) are wiped out.

I made an attempt to improve the copy, and even added a few "i understand" checkboxes, but would love your feedback.

Current is top row, proposed is bottom:
https://www.lucidchart.com/documents/view/eed48806-9d4c-48ea-b333-778ebdf840e1

**Comment by pdehaan** [comment]
@ryanfeeley 
I notice you switched from "erase any Sync data" to "erase any browsing data" and "erase my data" in your proposals.

Also, not sure I know what "Must be at least 8 unforgettable characters" means. What would make a character particularly memorable? Why not just stick with the olde trusted (and well translated) "Must be at least 8 characters" string that we have?

**Comment by ryanfeeley** [comment]
> I notice you switched from "erase any Sync data" to "erase any browsing data" and "erase my data" in your proposals.

Yeah, it's deliberately inconsistent so that:

1. it's less monotonous
1. there's more chances of it clicking in their minds

But, I'm not totally confident in the approach, hence why I'm looking for pro copy help.

The "Must be at least 8 characters" edit is an attempt for users to understand the importance of remembering the password. The idea would be the discourage future resets, though I don't think the copy achieves this.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - can you triage this as you see appropriate?

**Comment by ryanfeeley** [comment]
@shane-tomlinson I've already got feedback from Michelle, a UR contractor, on this and will be meeting her in an hour.

**Comment by rfk** [comment]
Is this covered by the new password-reset flow going live next train?  Adding it to that milestone on the assumption that it is.

**Comment by ryanfeeley** [comment]
@rfk Ready to go as far as I am concerned.

**Comment by rfk** [comment]
OK thanks, I'll close out this bug in favour of the ones already active in the FxA-72 milestone
