### ISSUE TITLE
Add campaigns to post-verification links

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#110]
So that we better can track post-verification email success, please add the following campaigns to the link:

Android Link:
https://www.mozilla.org/en-US/firefox/android/?utm_source=email&utm_medium=email&utm_campaign=fx-account-verified

iOS Link:
https://www.mozilla.org/en-US/firefox/ios/?utm_source=email&utm_medium=email&utm_campaign=fx-account-verified

Connect another Device button and text link alternative:
https://www.mozilla.org/en-US/firefox/sync/?utm_source=email&utm_medium=email&utm_campaign=fx-account-verified

**Comment by vladikoff** [comment]
Config needs to be updated in https://github.com/mozilla/fxa-auth-server/blob/master/config/index.js#L177

and https://github.com/mozilla/fxa-auth-mailer/blob/master/config.js#L109

and the campaign link needs to be specific to the post-verify email
