### ISSUE TITLE
links within buttons in verification email are almost impossible to read in zoho mail

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#119]
Brought over from https://github.com/mozilla/fxa-bugzilla-mirror/issues/128

--------------------------------------

From https://bugzilla.mozilla.org/show_bug.cgi?id=1246080

Created attachment 8716185
Screen Shot 2016-02-05 at 11.27.11 AM.png

Step to reproduce : 

Open a new Sync Account. Go to verification mail. 

Actual Result 

Button text is not visible clearly. 

Expected Result 

Button text should be visible.

--------------------------

The reporter mentioned zoho mail. I use zoho mail. I confirm this is a problem:

![screen shot 2016-02-10 at 09 13 42](https://cloud.githubusercontent.com/assets/848085/12943049/9b8f3102-cfd6-11e5-9434-85e632326315.png)

--------------------------

If you look closely, "Activate now" is there, it's just very difficult to see because zoho adds their own style to links.

We add text color styling to the containing `td` element, but not the link itself. Zoho uses CSS to style the link. We should override Zoho's styles by providing styles on the link itself.

![screen shot 2016-02-10 at 09 15 20](https://cloud.githubusercontent.com/assets/848085/12943115/fe08474c-cfd6-11e5-82df-106375888dc9.png)

**Comment by TDA** [comment]
@shane-tomlinson All three of our verification emails: {verify, verification_reminder_first, verification_reminder_second}, where we use "Activate now" are styled at the `a` link level. I cannot see this in zoho mail atm:
<img width="1440" alt="screenshot 2016-06-23 18 04 46" src="https://cloud.githubusercontent.com/assets/432707/16324828/fedfd036-396c-11e6-8892-84fcdd334866.png">

Closing this.
