### ISSUE TITLE
Post-verification links shouldn't include 'en-US' in localized e-mails

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-auth-mailer#122]
This might have been changed recently in issue #110, or has been broken for a long time, but links in the post-verification e-mail are redirecting our global audience to English pages, even when the pages are translated.

We should remove en-US locale code from the links. For instance https://www.mozilla.org/en-US/firefox/android/?foo=… should be https://www.mozilla.org/firefox/android/?foo=…, etc.

**Comment by vladikoff** [comment]
Fixed, thanks! Will be in the next production deploy.
