### ISSUE TITLE
Establish baseline click-through rate of post-verification email

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#127]
In #110 we added utm_\* params to the add-a-second-device links in our post-verification email.  This is a follow-up issue to get some stats on the click-through rate of those links, so we can compare the effectiveness of these vs the new sms install link.

**Comment by philbooth** [comment]
@rfk to triage

**Comment by rfk** [comment]
@ryanfeeley coordinated to get us some preliminary results for this, and it looks like we’re getting just under 5% click-through on the links in these emails.

**Comment by seanmonstar** [comment]
Moved to https://github.com/mozilla/fxa-auth-server/issues/1857
