### ISSUE TITLE
Malformed utm_campaign links in post-verification email?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#128]
We got the first round of results from the metrics on our post-verification emails.  In addition to many successful click-throughs with `utm_campaign=fx-account-verified`, there also seem to have been a handful that came through with the following:

* `utm_campaign=`fxaccountverifiedThis`
* `utm_campaign=`fx-account-verified>`

I wonder if it's caused by a bad rendering of the link in a particular email client?  The rate is very small but we should check if there's anything obvious that could be causing this.

**Comment by vladikoff** [comment]
@vbudhram did you see any issues with the templates and utm_params? (where it would not format the link properly)

If not please close this

**Comment by vbudhram** [comment]
No didn't see any issues with the html or text rendering of the email utm params. I updated the mailer tests in https://github.com/mozilla/fxa-auth-mailer/pull/190 to verify utm links too. Closing for now.
