### ISSUE TITLE
Create a more generic post-verification email for non-sync signups

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#129]
In [1] @ryanfeeley notes that our very sync-focussed post-verification email is sent to all users, even if they signed up for something other than sync, like AMO.  There's probably something better we can do.

@ryanfeeley thoughts on whether we should send a different, more generic email in its place, or just not send one at all?

[1] https://github.com/mozilla/fxa-auth-mailer/issues/66#issuecomment-198057898

**Comment by ryanfeeley** [comment]
I can't think of an email a new AMO user would want to would want to get after verifying their account. Not sure there is a generic solution here. I think we should just only send the email to Sync users.

**Comment by rfk** [comment]
Closing this in favour of https://github.com/mozilla/fxa-auth-server/issues/1249 since I believe the fix will actually have to happen in the auth-server

**Comment by rfk** [comment]
Let's morph this into a "make a more generic post-verify email" using the following proposal from @johngruen in https://github.com/mozilla/fxa-auth-server/issues/1249#issuecomment-220369847

--------

Hey @ckarlof @ryanfeeley et al...seeing this with Test Pilot is particularly jarring. Proposal:

I like the verification email, but maybe we could say something like the following if a user signs up through a non-sync endpoint:

# Account verified

Congratulations on signing into **Test Pilot** with your new Firefox Account.

Did you know you can use the same account to sync your bookmarks, history, passwords and more for Firefox on Desktop, IOS and Android.

### Some kind of sync cta page button/link

**Comment by rfk** [comment]
@ryanfeeley no particular rush, but when you get a chance I think you own the next action on this bug - review the suggested copy and see if you're happy to move forward with it.

**Comment by rfk** [comment]
Or, close the bug if your comment at [1] still stands :-)

[1] https://github.com/mozilla/fxa-auth-mailer/issues/129#issuecomment-198092311

**Comment by ryanfeeley** [comment]
@johngruen My feeling is that Test Pilot users who just created the requisite FxA don't need a post-verification email. What are your thoughts?

**Comment by rfk** [comment]
I'm going to go with "Test Pilot users don't get a post-verification email", let's open a fresh bug with concrete copy proposal if we decide to revisit this.
