### ISSUE TITLE
"reset your password" link on "Your password has been reset" email does not prefill email on the content server

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#157]
![reset-link-no-prefill-email](https://cloud.githubusercontent.com/assets/848085/15208414/5a7f8cd0-1823-11e6-8cdf-b06110fb6aa9.gif)

Ref #151

**Comment by vbudhram** [comment]
@shane-tomlinson This was removed as part of https://github.com/mozilla/fxa/tree/master/features/FxA-72-reset-password. I believe the reasoning was that it gives the user and extra chance to not reset their password. @ryanfeeley can you confirm?

**Comment by shane-tomlinson** [comment]
@ryanfeeley and I discussed on Friday. He asked me to add the `reset_password_confirm: false` query parameter so that the form submits automatically when the URL is opened.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Speaks the truth @vbudhram.
