### ISSUE TITLE
Resend verification mail doesn't work

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-auth-mailer#160]
I'm creating and deleting accounts and correctly get the initial verification email almost immediately.

However, if I hit "resend" in the FxA interface, or hit the "Verify Email" button in Firefox itself, I'm told a mail was successfully resent, but the verification rarely comes. After about 10 minutes of waiting, I ended up mashing the "Verify Email" button around 20 times before it finally hit the rate limiter and said it was unable to send the email. A minute after that I got 2 of the mails - I've no idea if the other 18 will arrive or not, but at a minimum they are very slow to arrive (as mentioned, the initial mail always seems to arrive immediately)

The account is skippy.hammond+test1 at gmail incase that helps.

**Comment by rfk** [comment]
We have an "smtp blackout period" that means we silently fail to resend the email within 10 minutes of account creation:

 https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L1053

TBH I don't recall why we have this; @dannycoates do you?

**Comment by rfk** [comment]
I wonder if we can remove it in favour of the more general you-cant-send-more-than-X-emails-in-Y-timeframe rate limiting provided by customs server.

**Comment by mhammond** [comment]
I also note that the request succeeded, so everything told me it was successfully sent, but it wasn't.

**Comment by dannycoates** [comment]
> TBH I don't recall why we have this; @dannycoates do you?

My memory of it was as a stop-gap anti-abuse measure to prevent an attacker from spamming emails they don't own.

> I wonder if we can remove it

I think so. According to https://github.com/mozilla/fxa-auth-server/pull/654#issue-30145603 it wasn't meant as a permanent feature anyway (wow, train-07... old school).

**Comment by rfk** [comment]
lol single-digit train numbers, those were the days!

**Comment by shane-tomlinson** [comment]
There is also a little thing worth knowing about the FxA web client, we only allow 4 clicks on the "resend" button. Of those 4 clicks, only 2 do anything. The other two clicks are ignored.

**Comment by mhammond** [comment]
FWIW, I would have considered it a "good experience" if that 10 minute limit and the magic above was dropped and a relatively aggressive backoff was implemented with the UI reliably reporting whether it failed or not.

**Comment by shane-tomlinson** [comment]
@rfk - Can you triage this as you see fit?
