### ISSUE TITLE
Add location information to confirm signin emails

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#162]
Follow on work. The original plans called for signin location information in the confirmation email. This was removed from the initial iteration so that we could move more quickly.

**Comment by rfk** [comment]
Ref https://github.com/mozilla/fxa-auth-mailer/issues/165

**Comment by rfk** [comment]
Moving this to the FxA-99 milestone

**Comment by shane-tomlinson** [comment]
This can be closed since #180 has merged.
