### ISSUE TITLE
Propose improved UX for signin emails

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#165]
Our current signin notification/confirmation emails are fairly bare-bones, and we'd like to improve them by adding things such as the location and local time of the login attempt.  @ryanfeeley could you please either the existing designs you had for this into in the "new signin to firefox" and "confirm signin to firefox" emails, or a new-and-improved version based on our discussion earlier today?

**Comment by ryanfeeley** [comment]
I have collected all of our emails into a large doc: https://docs.google.com/a/mozilla.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit?usp=sharing

With respect to time/location details, I propose we simply improve that portion of the email. Would be great to show city in locale language, and time in locale’s format.

CURRENT:
Firefox 47, Mac OSX 10.11 
2016-06-03 19:20 UTC

PROPOSED:
Firefox 47, Mac OSX 10.11 
Toronto, ON, Canada
3:20 PM Friday, June 3, 2016

**Comment by ryanfeeley** [comment]
@rfk If we wanted to add IP we could do:

PROPOSED:
Firefox 47, Mac OSX 10.11 
Toronto, ON, Canada (66.207.193.21)
3:20 PM Friday, June 3, 2016

**Comment by TDA** [comment]
@ryanfeeley We have `City, Country` data, but not `City, Province, Country`. Is that all right?

**Comment by ryanfeeley** [comment]
@TDA Absolutely fine.

**Comment by TDA** [comment]
@rfk @ryanfeeley @shane-tomlinson @vbudhram @vladikoff 

Prototypes:
#### With full location data (country, city, ip, time_zone):
![screenshot 2016-06-28 16 08 43](https://cloud.githubusercontent.com/assets/432707/16436252/292f8b00-3d51-11e6-970f-4e3093ad7c55.png)

#### With semi location data (country, ip, time_zone):
![screenshot 2016-06-28 16 54 01](https://cloud.githubusercontent.com/assets/432707/16436260/3d7ab102-3d51-11e6-9cd7-95701ceb1454.png)


#### With no location data (only ip, and server local time):
![screenshot 2016-06-28 16 08 34](https://cloud.githubusercontent.com/assets/432707/16436270/52a5fabe-3d51-11e6-8ff2-54da6501d65b.png)

What should be the text that accompanies the location data (especially if we have incomplete data that is)? Something along the lines of `The location is approximate and determined by the IP address it was coming from.`? (Google says that).

**Comment by vbudhram** [comment]
> The location is approximate and determined by the IP address it was coming from.

I do believe having some text saying that the location is an approximation would be useful. However, adding that caption to the footer seems like it would make it more cluttered, since we have the company address and reset password information in footers as well.

**Comment by ryanfeeley** [comment]
Looking great, degrading gracefully too.

**Comment by TDA** [comment]
From mtg with @vbudhram and @ryanfeeley :
1. Display the date/time in the timezone of the login, and NOT the locale from which the user signed up.
2. Use 24-hour clock.
3. Good-to-have : Represent the date-time in locale-specific manner (m-d-y vs d-m-y, etc.)

**Comment by rfk** [comment]
If this above summary differs from what's in the feature doc, please update the feature doc accordingly.
