### ISSUE TITLE
Include utm_* metrics params in all our email links

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#182]
In [1] our success metrics include the ability to see whether users are clicking through links from our security-related emails.  Let's support this by including utm_* on all embedded links in our emails.

We have prior art for this in the post-verification email, which includes the following query params:

```
utm_source=email&utm_medium=email&utm_campaign=fx-account-verified
```

I like the pattern here of using `utm_source` and `utm_medium` to indicate a link of followed from an email, and `utm_campaign` to indicate which email.

[1] https://github.com/mozilla/fxa/tree/master/features/proposed/FxA-99-improved-login-notification#metrics

**Comment by vbudhram** [comment]
Does it make sense to include some time information in utm params? Specifically, `utm_sent`, so that we can see when the email was sent, and when the user clicked the link?

**Comment by rfk** [comment]
That's an interesting idea, but I think we should defer it until we have a concrete graph we want to produce in mind.

**Comment by vbudhram** [comment]
Went through and looked at all links and buttons in our emails. Below summarizes what
I think is a good starting place for the utm_* params. 

Notes:
- All emails will be appended with utm_source=email&utm_medium=email.
- `utm_campaign` corresponds to the email type sent
- `utm_context` corresponds to which link/button was clicked

@rfk @ryanfeeley Do these make sense? This what you were thinking?

* Welcome!
  * utm_campaign = fx-account-welcome
  * utm_context = 
    * Activate now button: fx-account-activate
    * Mozilla Support: fx-account-support
    * Privacy Policy: fx-account-privacy

* Hello again. (Reminder email 1)
  * utm_campaign = fx-account-hello-again
  * utm_context = 
    * Activate now button: fx-account-activate
    * Mozilla Support link: fx-account-support
    * Privacy Policy link: fx-account-privacy

* Account verified!
  * utm_campaign = fx-account-account-verified
  * utm_context = 
    * Android link: fx-account-connect-android
    * iOS link: fx-account-connect-ios
    * Connect another device button: fx-account-connect-device
    * Mozilla Support link: fx-account-support
    * Privacy Policy link: fx-account-privacy

* New sign-in to Firefox (Confirm Sign-in)
  * utm_campaign = fx-account-new-signin    
  * utm_context = 
    * Confirm sign-in button: fx-account-confirm-signin
    * Please change password link: fx-account-change-password
    * Mozilla Support link: fx-account-support
    * Privacy Policy link: fx-account-privacy

* New sign-in to Firefox (New device Sign-in)
  * utm_campaign = fx-account-new-device-signin
  * utm_context = 
    * Please change password link: fx-account-change-password
    * Mozilla Support link: fx-account-support
    * Privacy Policy link: fx-account-privacy

* Forgot your password?
  * utm_campaign = fx-account-forgot-password
  * utm_context = 
    * Remember password? Sign in link; fx-account-remember-password
    * Reset password button: fx-account-reset-password
    * Mozilla Support link: fx-account-support
    * Privacy Policy link: fx-account-privacy

* Your password has been reset
  * utm_campaign = fx-account-password-reset
  * utm_context = 
    * Remember password? Sign in link; fx-account-remember-password
    * Reset password button: fx-account-reset-password
    * Mozilla Support link: fx-account-support
    * Privacy Policy link: fx-account-privacy

* Password change successfully
  * utm_campaign = fx-account-password-change-success
  * utm_context =     
    * Reset password link: fx-account-reset-password
    * Mozilla Support link: fx-account-support
    * Privacy Policy link: fx-account-privacy

**Comment by rfk** [comment]
@vbudhram I like it!  My one suggestion would be to use "fxa-" rather than "fx-account-" as a prefix in `utm_context`, just to keep the link a tiny bit short.  But that's pretty close to bikeshedding, so up to you :-)

Per #188 we should also add params to the main action links in each email, both the button form and the plain-text "Alternatively" link.  /cc @shane-tomlinson
