### ISSUE TITLE
Remove the unneeded templates: suspicious_location

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#183]
The [suspicious_location](https://github.com/mozilla/fxa-auth-mailer/blob/master/templates/suspicious_location.html#L39) templates were put together very quickly w/o thinking about best l10n practices. `{{t "Location: " }} {{ location }}` makes assumptions about the format of the string for all locales, which is prone to breaking. Now that we have time on our side, we should update these strings to follow best practices. 

I believe the above referenced string should be:

``` js
{{t "Location: %(location)s", location }}
```

We'll have to ensure our `t` helper function can do string interpolation correctly.

**Comment by rfk** [comment]
Before we go too far down the path of cleaning up those emails, I think we should get @davismtl to take a look, and decide if we're realistically ever going to use them.  They were originally draft in case we needed to send a post-hoc "whoops, look at all this suspicious activity that happened on your account" email, but the new emails that include this info on very signin may mean we never have to send one of those.

**Comment by davismtl** [comment]
@rfk Was this meant to retroactively email everyone? In what context was this email intended? (what would trigger it)
I don't see this 60 day login "journal" being necessary with all the new email notifications we will be sending out. Additionally, device view in settings might also cover a part of this. (so long as the user checks)

**Comment by davismtl** [comment]
After speaking to @rfk , I think a better solution was adopted and that this isn't necessary in the foreseeable future.

**Comment by rfk** [comment]
Morphing into a "remove the unneeded templates" bug.
