### ISSUE TITLE
If a user clicks on "If this wasn't you, (change|reset) your password" in the security emails, we should be notified.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#185]
This is @ryanfeeley's idea from the original signin confirmation designs, but I think it has merit for _all_ emails that include the text "If this wasn't you, (change|reset) your password." We have a lot of monitoring to see if there is a spike in certain types of errors, but it would be nice if we could use crowd-sourcing as another data point. Of course, some users may mistakenly click the link and we'll receive a notification. Perhaps to guard against this, we require the number of notifications to cross a pre-defined threshold for a given time frame. If the number of notifications crosses the threshold, alerts are sent to the team that we may be under attack.

**Comment by shane-tomlinson** [comment]
The initial idea on how to make this idea a reality is to add a query parameter to the "If this wasn't you..." link that indicates to the content server "this user came from a security email." The content server would see the query parameter and send a report, either in metrics or to a standalone endpoint. We then do some metrics pipeline foo and generate notifications.

**Comment by ryanfeeley** [comment]
@shane-tomlinson What if we take them to a page that gets confirmation of their intent and track that?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson What if we take them to a page that gets confirmation of their intent and track that?

I feel a bit slow post a too-hot-to-run-run. Would this be a screen in addition to the password change/reset screen? Could we alter the text of those existing screens to say something along the lines of "You are requesting to change/reset your password in response to a security email..."?

**Comment by ryanfeeley** [comment]
In our current footer we say: If you suspect that someone is trying to gain access to your account, **please report it to us**. 

That link could go to a page that says:

* Does this sign-in attempt look suspicious to you?
* Details (client, location, date, etc)
* Notify us (primary)
* Nevermind (secondary)

Clicking "Notify us" could direct the person to a password reset screen with an additional on top that says. "If you are certain that someone has access to your password, but not your email, you still might want to reset your password here, and also change it anywhere else you used this password."

I think a feature doc is required. What do you think @shane-tomlinson?

**Comment by ryanfeeley** [comment]
@davismtl Hey Alex, let's talk about where/how we will create feature docs for FxA. This one involves email and web, but not the browser.

**Comment by rfk** [comment]
FYI in #182 we're talking about adding params to the links in our emails, to identify what email they came from.  May be useful here, although it sounds like the discussion is heading towards using a separate landing page for this.

**Comment by davismtl** [comment]
@ryanfeeley I've sent you a meeting request for tomorrow. We can talk about getting this feature document ready.

**Comment by rfk** [comment]
@davismtl did the above-mentioned meeting occur?

**Comment by davismtl** [comment]
The meeting did occur but other pressing matters diverted the meeting topic.
I've added it to our 1:1 agenda for tomorrow.

**Comment by davismtl** [comment]
Just leaving a link to all our email templates. Whatever solution we come up with should work for all of these: https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#

**Comment by davismtl** [comment]
@rfk We plan on integrating links like this to account login confirmation email and device management deletion email as signals.
Do you agree that we should just define a standard so that all future email templates can just follow said standard?

**Comment by rfk** [comment]
Yes, I agree, a single standard for all emails makes sense.

**Comment by davismtl** [comment]
In summary, things to think about and investigate (perhaps create a feature card):
Do we want a dedicated landing page for users that click on "no this wasn't me"? Do we want to capture more signals past the click? Is sending the user to the change password view sufficient?

**Comment by vbudhram** [comment]
FWIW, we can now see what users are doing from our sign-in confirmation emails. The attached graph says that from this email,  99% goto the complete_signin view verses 1% goto change password view.

https://app.datadoghq.com/graph/embed?from_ts=1471484740396&to_ts=1471571140396&token=15de6d04e44196ed21cbfbc65ab0cbf54760e2ae65b394ae3890ad2f1c98f51c&height=300&width=600&legend=true&tile_size=m&live=true

This does seem like a pretty low number, but it only counts interactions from the email. The user could change their password by manually logging in and changing it.

**Comment by davismtl** [comment]
Let's keep an eye on it. The data has been coming for just 4 days so I think we'll have a big enough sample in a few days. Too hard to tell what % of users are clicking the resetting password. From a glance it seems even smaller than <1%. Might also be nice to look at that data in a different way. It's a little hard in those datadog charts.

**Comment by rfk** [comment]
Also, 1% of a big number is still a big number :-)

**Comment by rfk** [comment]
Given "let's keep an eye on it" I am going to put this back into the backlog and remove it from the sign-in confirmation milestone.  We'll do an analysis of the reset rate when we finish up the sign-in confirmation milestone, and we can take a fresh look at adding additional UI for this if/when we decide we need it for a new feature.

**Comment by seanmonstar** [comment]
Moved to https://github.com/mozilla/fxa-auth-server/issues/1858
