### ISSUE TITLE
Add location information to verify_email, reset password and password changed templates

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#189]
For example, password reset is sometimes used to compromise accounts. Perhaps we should show location information to these emails too.

cc @ryanfeeley - if you don't think it'd provide any value, feel free to close.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Current emails. Are we sending suspicious sign-in notices yet? https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#

**Comment by rfk** [comment]
> Are we sending suspicious sign-in notices yet? 

No, and per [1] I have no reason to believe we ever will.  The user gets more timely notice about login attempts from the "new login" and/or "confirm signin" emails.

[1] https://github.com/mozilla/fxa-auth-mailer/issues/183#issuecomment-234924763

**Comment by vladikoff** [comment]
@ryanfeeley which emails should we add this to?

**Comment by ryanfeeley** [comment]
On reset request, you could add the location information after replacing the line of copy above it to be: Click the button within the next hour to set a new password for your Firefox Account. The request came from the following device:

**Comment by ryanfeeley** [comment]
Proposal for verification email: <img width="399" alt="screenshot 2016-12-16 14 28 58" src="https://cloud.githubusercontent.com/assets/68213/21276949/d2cbb996-c3a1-11e6-8748-220939e4f190.png">

**Comment by vladikoff** [comment]
From mtg:

Add the location info into the following:

* verification email with text tweaks
* "reset your password"

**Comment by ryanfeeley** [comment]
from password change notification…

CURRENT

* Your Firefox Account password has been successfully changed.

PROPOSED

* Your Firefox Account password has been successfully changed from this device: (include info)

**Comment by ryanfeeley** [comment]
kill date too

**Comment by ryanfeeley** [comment]
<img width="642" alt="image" src="https://cloud.githubusercontent.com/assets/68213/21278496/809be224-c3a9-11e6-9318-78256523b0b1.png">
https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#

**Comment by seanmonstar** [comment]
> kill date too

While the date doesn't seem useful many times since the timestamp for when the email received is probably pretty close, it seems like it is useful for when delivery was delayed a while.

**Comment by vbudhram** [comment]
@ryanfeeley @vladikoff Do you guys know where I could find the Mozilla hosted version of this image? The one on the sync homepage is composed of several tiny images.

<img width="394" alt="screen shot 2016-12-21 at 11 02 08 am" src="https://cloud.githubusercontent.com/assets/1295288/21396089/f25a4b28-c76c-11e6-913d-c9b18f039f9b.png">

**Comment by vladikoff** [comment]
@vbudhram this needs to be uploaded to `https://image.e.mozilla.org/lib/....`. 
Just like: https://image.e.mozilla.org/lib/fe9915707361037e75/m/2/fxlogojg.gif

Meanwhile while we wait on that let's just use the Firefox Logo in the new template and then update it.

@jbuck @jrgm do you remember to how to do that?

**Comment by vbudhram** [comment]
> Meanwhile while we wait on that let's just use the Firefox Logo in the new template and then update it.

👍

**Comment by vbudhram** [comment]
@ryanfeeley I have a couple q's from updating templates.

- What should title be on account verify email? Different mock-ups use `Ready, set sync`, `Ready, set, sync` and sync homepage use `Ready, Set, Sync!`
- In verify email, should we use the `→`, mocks have it with and without. FWIW I like the arrow :)
- The device text in password change email was not specified, what should it be? Since the action occurred before the email, I was thinking something like `The request was performed on the following device:`

**Comment by vladikoff** [comment]
@vbudhram The final version of what it should be is here: https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit

**Comment by ryanfeeley** [comment]
@vbudhram 

> What should title be on account verify email? Different mock-ups use Ready, set sync, Ready, set, sync and sync homepage use Ready, Set, Sync!

The second one was from Michelle, which is: Ready, set, sync

> In verify email, should we use the →, mocks have it with and without. FWIW I like the arrow :)

I would like to start using arrows for "happy path" buttons. Possible to test with Email on Acid? I ♥︎ unicode, like the next person, but want to make sure it renders widely.

> The device text in password change email was not specified, what should it be? Since the action occurred before the email, I was thinking something like The request was performed on the following device:

Updated in doc to: Your Firefox Account password was successfully changed from the following device:

**Comment by vladikoff** [comment]
Here's an optimized PNG 21kb: 

![image](https://cloud.githubusercontent.com/assets/128755/21400558/b2774512-c77e-11e6-8767-dca024e16809.png)


cc @jbuck

**Comment by vladikoff** [comment]
updated link above^ , @ryanfeeley check if have time

**Comment by vladikoff** [comment]
@jbuck @vbudhram updated with a crispy jpg: http://v14d.com/g/choose_what_to_sync_devices2x.jpg
