### ISSUE TITLE
Apostrophe showing it's unencoded entities in our email?

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#191]
Not sure if it's Google not rendering entities, or something we control, but the "didn’t" looks pretty gnarly. 
<img width="609" alt="screenshot 2016-07-28 16 09 24" src="https://cloud.githubusercontent.com/assets/68213/17227769/eac434fc-54dd-11e6-93e0-389609bc8613.png">

**Comment by vladikoff** [comment]
We have different `'` in here: https://github.com/mozilla/fxa-auth-mailer/search?utf8=%E2%9C%93&q=if+you+didn%27t

**Comment by ryanfeeley** [comment]
Hopefully clears things up: "Why are all my apostrophes missing?"
https://www.campaignmonitor.com/blog/how-to/2008/04/why-are-all-my-apostrophes-mis/
