### ISSUE TITLE
Device description for FxiOS is mildly confusing

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#193]
Trying out the sign-in confirmation flow on Firefox for iOS, I got the email saying:

![screen shot 2016-08-04 at 15 14 58](https://cloud.githubusercontent.com/assets/34695/17391088/97a3cd40-5a56-11e6-9c33-70b053e23efb.png)

At first I thought "Firefox iOS 5, iOS 9.3" was a bug, somehow duplicating the string "iOS".  Then I realized it was saying "Firefox for iOS, version 5, running on iOS 9.3".  I wonder if there are small changes we could make that would increase comprehensibility of these device descriptions?  /cc @ryanfeeley

**Comment by shane-tomlinson** [comment]
This would be  a problem on the "New device login" email  as well.

**Comment by philbooth** [comment]
Could special case this in the user agent parser to return `Firefox Mobile` instead of `Firefox iOS`, which matches the parsed Android string?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Seeing as these emails only go to Sync users, who in turn must also be Firefox users, is the operating system alone enough? I tend to think yes.

**Comment by shane-tomlinson** [comment]
> who in turn must also be Firefox users, is the operating system alone enough?

Mostly true, we have some partner browsers to consider. We could determine if the browser is Firefox or Firefox Mobile, and if so, only show the OS and if not, show both the browser and OS?

**Comment by ryanfeeley** [comment]
We should change them from current → proposed:
* Firefox 47, Mac OS X 10.11 → Firefox on Mac OS X 10.11
* Firefox 48, Windows 10 → Firefox on Windows 10
* Firefox Mobile 48, Android 6 → Firefox on Android 6
* Firefox iOS 5.1, iOS 9.3 → Firefox on iOS 9.3
