### ISSUE TITLE
Add signin-authorization email

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#196]
Ref https://docs.google.com/document/d/1qbzfA21T0HoHpgxXlpO26qcCQDx2v0PUbcoHW9XtxQQ

Could use some @ryanfeeley foo.

Initial mockup from @rfk:

<img width="269" alt="screen shot 2016-08-08 at 12 00 07" src="https://cloud.githubusercontent.com/assets/848085/17477848/8e3e23f2-5d5f-11e6-9728-fa8a1ea9a9c9.png">

**Comment by ryanfeeley** [comment]
@shane-tomlinson What I don't understand about this process yet is why we don't simply send the verification automatically? Or put the request to send the authorization mail on a page with a captcha?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson What I don't understand about this process yet is why we don't simply send the verification automatically? 

Let's chat on vidyo about the flow, I'm open to automatically sending the flow unless @rfk has a good reason why we should not. This particular bug is slightly different, I'm trying to get your input on what the sent email for this use case will look like.

> Or put the request to send the authorization mail on a page with a captcha?

2 issues with captchas here:

1) Captchas require 3rd party code, which is verboten. 
2) Captchas are useful to prevent certain types of automated attacks, but they offer different protection to this feature. With signin authorization, we provide similar protection to signin confirmation, but we do it earlier in the flow (pre-password check), initially in response to a user being blocked or rate limited.

**Comment by rfk** [comment]
no catpchas

**Comment by rfk** [comment]
> I'm open to automatically sending the flow unless @rfk has a good reason why we should not

I'm open to sending it automatically in all cases, if it improves the overall flow
