### ISSUE TITLE
Add parameter to links in text-only emails

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#197]
@vbudhram Is anyone clicking the links in our text only emails? Would be good to differentiate them.

**Comment by davismtl** [comment]
@ryanfeeley What will this help you answer? What would you do with the results? Your answers would help us prioritize.

**Comment by ryanfeeley** [comment]
@davismtl @vbudhram 

According to [this DataDog dashboard](https://app.datadoghq.com/dash/172590/fxa-content---emails?live=false&page=0&is_auto=false&from_ts=1471579200000&to_ts=1472011199999&tile_size=m&fullscreen=false)…

1.8% of registering users click the long link, while 4.8% of users signing in click the long link.

This tells me that it's safe to remove the long link from the verifcation because the link is so large that people are clicking it accidentally.

But that 4.8% for confirm sign-in should be removed immediately because users are probably thinking that it has a different purpose.

How to proceed? Issues to remove both?

**Comment by ryanfeeley** [comment]
@davismtl Good question. I suppose it's just like knowing that browsers are visting a web page. I am not sure the information is valuable, only in that it will help us prioritize our text-only email quality work.

**Comment by vbudhram** [comment]
@ryanfeeley Is the bigger question here, how many people view text only emails?

**Comment by ryanfeeley** [comment]
@vbudhram Yeah, handy to know, but not crucial. Good to know how many users have less capabilities.

**Comment by seanmonstar** [comment]
Moved to https://github.com/mozilla/fxa-auth-server/issues/1861
