### ISSUE TITLE
export the templates to l10n

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-mailer#20]
move the export of the email templates from content-server to here

**Comment by shane-tomlinson** [comment]
@zaach and @dannycoates - how do we want to get the strings from the auth mailer to the l10n crew? Do we want to extract strings from both here and the fxa-content-server repo, bundle them into the same package, and ship them off to be localized?

**Comment by zaach** [comment]
Current strategy is to extract and merge these strings with the templates from the l10n repo, then they must be copied over to the l10n repo like usual.
