### ISSUE TITLE
Add missing state information on geo profile emails

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-mailer#201]
Something I noticed in our geo profiled emails, is that it doesn't include state information for US.

<img width="386" alt="screen shot 2016-08-19 at 1 34 25 pm" src="https://cloud.githubusercontent.com/assets/1295288/17818538/16ab081c-6612-11e6-96a2-164832866f78.png">

I would expect this to be read as `Orlando, Florida, United States (estimated)` instead of `Orlando, United States (estimated)`.

@ryanfeeley Thoughts?

**Comment by TDA** [comment]
I believe this was decided to be `City, Country`, we do however have state data in case we need to show that. @vbudhram

**Comment by vbudhram** [comment]
@TDA Yea, you are right we did agree on it. Just wondering in hindsight, if we should add the state information for US territories. Not sure if putting an edge case for US makes sense though.

**Comment by ryanfeeley** [comment]
@vbudhram If we can use the two-letter abbreviation for the state and the three-letter abbreviation for United States, I am all for it.

In the above example:

* Orlando, FL, USA

**Comment by vbudhram** [comment]
@ryanfeeley That seems fair, I don't think it is a huge priority so going to keep it in backlog for a bit.

**Comment by seanmonstar** [comment]
Imagine getting `Paradise, United States`. Then look how many it could be: https://en.wikipedia.org/wiki/Paradise_(disambiguation)

I think this isn't as much of an issue in geographically smaller countries, but the USA is absurdly large. I wonder if other sufficiently large countries have a similar issue.

**Comment by TDA** [comment]
I can imagine @pdehaan smirking behind the scenes ;)

**Comment by vladikoff** [comment]
@TDA did we include this funtionality or was it just prototyping ?

**Comment by TDA** [comment]
@vladikoff Its there, just need to use it in the auth-server/mailer templates. We have state data :)

**Comment by vladikoff** [comment]
>  just need to use it in the auth-server/mailer templates.

@TDA 🍰

**Comment by ryanfeeley** [comment]
@seanmonstar Good one. I've heard Springfield is even worse (a possible reason for town name on Simpsons) https://en.wikipedia.org/wiki/Springfield_(disambiguation)

**Comment by vladikoff** [comment]
ping @TDA

**Comment by TDA** [comment]
@vladikoff my bad, definitely will have a PR ready before thursday :)

**Comment by vladikoff** [comment]
> @vladikoff my bad, definitely will have a PR ready before thursday :)

Don't worry, we took care of it. 

<img src=https://i.imgur.com/NXAbM9g.gif width=190 />

**Comment by TDA** [comment]
@vladikoff Thanks and sorry vlad!
