### ISSUE TITLE
No error reported/handled on failure to send SMTP message

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-mailer#207]
There's a bit of a serious bug here: https://github.com/mozilla/fxa-auth-mailer/blob/master/lib/verification-reminders.js#L31-L37

If that attempt to send mail fails (e.g., MTA refuses the connection, or refuses auth creds, or a misconfiguration tries to send the email to something that is not listening, etc., etc.), the error is not handled and nothing but success is reported in the logs (and in the case of verification reminders, the reminder record is removed). I'll leave it to you to how best to properly handle the error. But since this code is somewhat patterned on previous code, I'm curious if there are other paths which don't handle an error from Mailer.prototype.send.

It might be useful also to change https://github.com/mozilla/fxa-auth-mailer/blob/master/mailer.js#L212 from `log.trace` to `log.error`.

**Comment by vladikoff** [comment]
> It might be useful also to change https://github.com/mozilla/fxa-auth-mailer/blob/master/mailer.js#L212 from log.trace to log.error.

This sounds like a good idea
