### ISSUE TITLE
How to ensure we always have the latest fxa-content-server-l10n?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#210]
This came up in the retrospective earlier this week, and I don't think we found a solid answer.  It's definitely worth solving though.  Discuss.

**Comment by shane-tomlinson** [comment]
IIUC, @jrgm pins the content server to a particular content-server-l10n repo sha, I'm assuming the l10n repo sha is updated in npm-shrinkwrap.json via some script. Could the same logic be used as part of the auth-server and auth-mailer, using the exact same config value?
