### ISSUE TITLE
iOS Gmail app email rendering weirdness

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#211]
Not sure why, but (at least) our confirm email copy is green and left-aligned on Gmail app for iOS.
![2016-09-12 16 32 45](https://cloud.githubusercontent.com/assets/68213/18639254/25683ed0-7e61-11e6-999a-8f4c4f4cd7d3.png)

@davismtl

**Comment by vladikoff** [comment]
This seems to be fixed in latest version of Gmail
![](http://v14d.com/i/5850755be43a5.jpg)

Ref https://blog.google/products/gmail/gmail-and-google-calendar-get-a-whole-lot-better-on-ios/
