### ISSUE TITLE
Reverse line order of IP and location in our emails

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#216]
I got some feedback from the UX team about the upcoming geo-location information.

Currently, in this order, we show:

* IP
* Location (if available)

Preferably, in this order, we should show:

* Location (if available)
* IP

Easy peasy @shane-tomlinson squeezy?

**Comment by jrgm** [comment]
I'll counter (from an engineer's POV) - the IP is what we absolutely know; the location is our best belief about  location. So IP first, then location is the appropriate order.

**Comment by seanmonstar** [comment]
I imagine from UX's (and an average user's) point of view, the location is something we immediately understand, but an IP address is some arcane Internet artifact.

**Comment by ryanfeeley** [comment]
@jrgm I think I took that original point in when designing it, but @seanmonstar is right, that most users will read location first. We do also qualify if the location is loosley approximated, so I think that helps.
