### ISSUE TITLE
Confirmation buttons in GMail turn green after being clicked

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#221]
Not sure if this happens for everyone or if I have a plugin that's interfering, but when I click on a verification link from FxA emails, the blue button turns green:

<img width="359" alt="screen shot 2016-10-04 at 16 47 37" src="https://cloud.githubusercontent.com/assets/848085/19081507/71031548-8a52-11e6-82be-e698d6438720.png">

**Comment by shane-tomlinson** [comment]
To be clear, this occurs in Fx Desktop - current release. But I have about 10 addons that block various things.

**Comment by shane-tomlinson** [comment]
It's possible this occurs because the button is an anchor element and gmail styles a:visited.

**Comment by vladikoff** [comment]
Tested this in clean Nightly and Stable and the buttons didn't turn green 🍏  :)
