### ISSUE TITLE
Insert a space in the unblock code?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#231]
For @ryanfeeley - we currently show an 8 character unblock code. It's not hard to use, but could be simpler. People are pretty used to working with 4 characters/digits at a time from their credit cards. Would it make sense to present the code in two 4 character sections?

```
A2FZ8KLG
```
vs

```
A2FZ 8KLG
```

If we do so, we'll need to strip all whitespace when the user enters the code on the content server. Currently we only trim the ends.

**Comment by ryanfeeley** [comment]
Nice idea! I suppose we could measure on the content server what % of users are pasting in this value. I suspect it's high.

Although adding a space is a lot less work and shouldn't make it worse for copiers.

**Comment by shane-tomlinson** [comment]
We decided to kill this idea.
