### ISSUE TITLE
signup verification email sent in english, reminders sent in dutch?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#233]
I have my browser set up in English, with German 3rd on the list. The office is connected via the Netherlands. On stomlinson.dev.lcip.org, I signed up, received my two verification emails a minute or two later, and this is what I see:

<img width="1096" alt="screen shot 2016-10-28 at 14 38 46" src="https://cloud.githubusercontent.com/assets/848085/19809379/fc5b53b8-9d20-11e6-93ca-f4f51fe8bc9d.png">

**Comment by vladikoff** [comment]
Hm for one I think we might need to remove the bad set of locales in stage.json config

**Comment by vladikoff** [comment]
Yea this this was a bad config on the fxa-dev boxes.

![](http://v14d.com/i/583f3b8461813.jpg)
