### ISSUE TITLE
Update the design of the verify_email template for sync

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-mailer#234]
#1533 There is a new design in https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#heading=h.bixwa795e5ma

![](http://v14d.com/i/581ce2889b8ee.jpg)

@ryanfeeley do we need more changes in that template?

**Comment by ryanfeeley** [comment]
Moved here, but still a work in progress with copy edits coming in. https://docs.google.com/document/d/19xcwVIUlUAo6GaNlbA7Rw_CA7r4vYp_2NZLUKFUKTTk/edit

**Comment by davismtl** [comment]
The CTA "Yes, let's sync" doesn't let me know that I am suppose to click on the button to confirm my email address. (yes, I know it's written in the small text)

I feel like there is risk for confusion here (especially after having watched the UT videos).

**Comment by ryanfeeley** [comment]
@davismtl Please suggest edits in the doc and add Michelle.

**Comment by davismtl** [comment]
Done

**Comment by vladikoff** [comment]
this will be in: https://github.com/mozilla/fxa-auth-mailer/issues/189
