### ISSUE TITLE
Details font style wrong on new email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#246]
<img width="726" alt="screenshot 2017-01-10 13 29 51" src="https://cloud.githubusercontent.com/assets/68213/21819676/b33f1a44-d73a-11e6-94bd-3480b22d2059.png">

Device details don't match spec: https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#heading=h.bixwa795e5ma

**Comment by vladikoff** [comment]
@ryanfeeley sorry, do you mean the colour or what?

**Comment by ryanfeeley** [comment]
Yes: details 13px/20px  #424f59

**Comment by vladikoff** [comment]
@ryanfeeley ah ok, thanks!
