### ISSUE TITLE
Apply for www.senderscorecertified.com

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-mailer#250]
This should help our mail deliverability with Outlook.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1318513#c19

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this?

**Comment by rfk** [comment]
Just to note, I've asked Travis to look into this from an ops and procurement perspective

**Comment by rfk** [comment]
> I've asked Travis to look into this from an ops and procurement perspective

The initial verdict from Ops is that they'd prefer not to have to deal with the expense and complexity of this directly, and we should instead look into switching to an email provider that has more of these sorts of services built-in by default, such as https://www.socketlabs.com/

**Comment by davismtl** [comment]
I like their slogan: "SocketLabs Has Email Performance Down To A Science"

They seem to be more than just an SMTP relay service. They seem to provide a lot of great tools and expertise. 

They're also more likely to be able to forward us to a different IP if we are having deliverability problems.

I'm certainly open to exploring new suppliers like them. Do we have any others we would like to compare them to?

**Comment by rfk** [comment]
There are a couple of other providers, e.g. sendgrid.  But I think some other properties within Mozilla use socketlabs already so that probably gives them an advantage in terms of e.g. existing risk assessments etc.

**Comment by davismtl** [comment]
I've used SendGrid in the past too.

I've tried to use Mandrill too but got kicked off because my sender score was too low. They specialize in transactional emails. (owned by MailChimp) http://www.mandrill.com/

I'm also all about easy, simple and fast risk assessments. (so long as pricing is comparable)

**Comment by vladikoff** [comment]
from mtg: closing
