### ISSUE TITLE
Move auth-mailer source to fxa-auth-server

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-mailer#253]
~~Maybe I just don't understand the intended code structure very well, but the way this repo has some code in the base directory and some under `/lib` feels a little bit messy to me. Not a huge deal obviously, but are we interested in tidying it up at all?~~

**Comment by vbudhram** [comment]
I am a 👍 for this. The code organization in the repo needs some work.

**Comment by rfk** [comment]
👍 :heart: 👍

**Comment by philbooth** [comment]
In the meeting it was discussed that maybe instead, we could just bring the auth mailer into the auth server repo en masse. In that case, we wouldn't want the lib directory, we'd want everything in the root of the mailer which would itself be a directory in the auth server.

**Comment by seanmonstar** [comment]
Definitely prefer the idea of just moving it into auth-server.

**Comment by rfk** [comment]
> we could just bring the auth mailer into the auth server repo en masse

I'm optimistic that this would simplify a lot of things for us!  If there are no objects from @jrgm or @jbuck on the deployment side of things then I'd definitely support this change.  It would also avoid some code duplication with the "db" stuff in this repo.

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-auth-mailer/issues/260
