### ISSUE TITLE
Sender name disappeared in train 80

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#262]
I noticed that the sender name "Firefox Accounts" has seemingly disappeared in train 80. Any ideas? 
<img width="599" alt="screenshot 2017-02-21 10 47 55" src="https://cloud.githubusercontent.com/assets/68213/23172301/545799e8-f823-11e6-8919-277913aa499c.png">

**Comment by vladikoff** [comment]
`From: accounts@firefox.com` <-- the 'From' field is broken in latest nodemailer...

**Comment by vladikoff** [comment]
In local-dev I get`Sender: Firefox Accounts <no-reply@lcip.org>` which is configured correctly, but `From:` is absent. 😕

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-auth-mailer/issues/263
