### ISSUE TITLE
Add App/Play Store badges to post-verification email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#264]
Lesson from Sync Fest – make it easier to download the app by putting a link directly in the email. We can use the same UTM params in the links used currently.

<img width="687" alt="image" src="https://cloud.githubusercontent.com/assets/68213/23410827/782c03a6-fd9e-11e6-8a04-a88d4d50c101.png">

**Comment by vladikoff** [comment]
I guess those need to be the translated, which is always fun ...

**Comment by seanmonstar** [comment]
Moved to https://github.com/mozilla/fxa-auth-server/issues/1859
