### ISSUE TITLE
Discuss changing destination of connect another device to FxA

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#265]
Now that @shane-tomlinson has built a great Connect Another Device experience, we should be using it in more places. Is our current experience ready to be deployed in this context? Let's discuss with @davismtl.

<img width="912" alt="screen shot 2017-04-17 at 10 07 35 am" src="https://cloud.githubusercontent.com/assets/68213/25091170/b0e7c310-2355-11e7-8ad9-464b0d41b442.png">

**Comment by davismtl** [comment]
We certainly need a page we can drive people to that can detect if you're on desktop and mobile and give you buttons or the SMS form accordingly.

Once we have that page, we can drive people to it from email, device manager, etc.

**Comment by ryanfeeley** [comment]
@davismtl  The Mozilla.org page does a decent job of this now, but I think a simpler page that we control would be better. We can also direct users from the "Not synced tabs… yet!" states in desktop.

**Comment by davismtl** [comment]
The mozilla page only does Android. We support both. Further more, we will be pre-populating forms and deeplinking in future phases. They will not support this (though we should look into helping them support it).

**Comment by rfk** [comment]
> We certainly need a page we can drive people to that can detect if you're on desktop
> and mobile and give you buttons or the SMS form accordingly.

+1, I'm strongly in favour of having a single landing page that we control that can be used for links of this sort.  Using https://accounts.firefox.com/connect_another_device?service=sync right now is not too bad at it and ISTM we can easily iterate it into shape for this purpose.

**Comment by vladikoff** [comment]
@ryanfeeley should we schedule a meeting for this?

**Comment by seanmonstar** [comment]
Moved to https://github.com/mozilla/fxa-auth-server/issues/1860
