### ISSUE TITLE
Should we keep this repo?

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-mailer#266]
Thanks to amazing teamwork, this code is now merged with the auth server. Is there reason to keep this repo around, or can we close it down?

**Comment by vladikoff** [comment]
>  or can we close it down?

What do you mean "close it down"? 
One useful thing we have here are the 9 open issues.

**Comment by seanmonstar** [comment]
I mean delete the repo. That'd include moving any open issues to the auth server repo.

**Comment by vladikoff** [comment]
> I mean delete the repo

-1 on that,  I think we have even older repos just in deprecated state.

**Comment by seanmonstar** [comment]
We have other repos of code that is no longer used anywhere? I'd propose deleting those too. What is gained by keeping repos around that aren't used or maintained?

**Comment by vladikoff** [comment]
I think it's best to move them to some fxa-archive org

**Comment by seanmonstar** [comment]
I still don't see what is gained from keeping them around. I feel deleting the repos is the best action, but if there's a stellar reason, we can at least put up messaging and disable issues on them.

**Comment by jrgm** [comment]
I'll note though, that new issues are being added to this repo. Can we block new issues being added here, instead of where the code lives?

**Comment by rfk** [comment]
I'm +1 to cleaning it up somehow at the very least, e.g. disabling issues etc and adding a big old "DONT USE THIS" to the readme.

**Comment by seanmonstar** [comment]
I've moved all the open issues to the auth-server. Next:

- Disable Issues on this repo
- Merge in a README stating this is 410 Gone.
