### ISSUE TITLE
Use one domain across our entire emails

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-mailer#267]
The phishing message displayed to Outlook users about our emails reminded me to check all the domain names in our emails.

At my past job, we would get flagged as spam if our images loaded from a different domain than the sender. Apparently this is something that is checked for phishing.

It turns out that we make this mistake. Our sender is accounts@firefox.com but our images are loaded from http://image.e.mozilla.org. Our privacy policy in our footer also points to mozilla.org too.

I don't recall if sub domains are also problematical but I know a few people that can answer that for us.

This is somewhat related to #4 from this link (essentially consistency is important). 
https://www.campaignmonitor.com/blog/email-marketing/2015/09/9-things-that-are-killing-your-email-deliverability/

**Also domain related**:
"Use the same domain in the email From field as the actual domain sending the message. Hotmail is especially scrupulous about this and likes to filter the messages as junk mail if the two domains do not match."

http://www.datavalidation.com/blog/How-to-Optimize-Your-Email-Deliverability-and-Maximize-Your-Email-Marketing-Revenues.html

Our smtp is amazonses.com so we also make this mistake. :-/

**Comment by jrgm** [comment]
@davismtl - can you re-file this in fxa-auth-server. This is no longer the authoritative repo for mailer issues. Thanks.

**Comment by davismtl** [comment]
Moved to: https://waffle.io/mozilla/fxa/cards/58f6919dadfc2600326a84b6
