### ISSUE TITLE
Add Firefox logo to emails from content server

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#28]
From @pdehaan in https://github.com/mozilla/fxa-content-server/issues/901

---------------------------

/summon @johngruen @ryanfeeley 

Should the emails from the server include the Firefox logo (like the site)?
AFAIK, we don't have an "Accounts/Sync" specific logo we could use instead, but not sure if this could benefit from more branding:

![verify_your_account_-_peterdehaan_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/557895/2683229/576c1470-c1a7-11e3-9334-eb52051b8794.png)

**Comment by ryanfeeley** [comment]
How feasible would it be to have the Firefox logo appear as it does on the accounts website? (straddling to top middle of the block, consistently in email clients)

![fxa-congratulations](https://cloud.githubusercontent.com/assets/68213/6397478/f71aa51a-bdb2-11e4-9f4d-557b1fadb523.png)

Would image inclusion increase spam rates?

**Comment by vladikoff** [comment]
Discussion is happening here: https://github.com/mozilla/fxa-auth-mailer/issues/35
