### ISSUE TITLE
Account emails are sent to Spam on "stable"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-mailer#33]
> from @groovecoder:

> Steps to reproduce:
> Sign up for an account on stable: https://oauth-stable.dev.lcip.org/console/clients
>
> Expected results:
> Email verification should show up in my Inbox
>
> Actual results:
> Email verification went to my Spam

Ref: https://github.com/mozilla/fxa-content-server/issues/2201
Moved from: https://github.com/mozilla/fxa-oauth-console/issues/26

**Comment by dannycoates** [comment]
set `"spam": false` in the config :trollface:

**Comment by rfk** [comment]
Closing in favourof #34
