### ISSUE TITLE
prod - "Verify your account" email ended up in gmail spam

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#34]
Reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1143176

> I wanted to create a Firefox Account, but didn't get the email, then i found it in my spam folder.

**Comment by rfk** [comment]
Possibly related to #33.  I was hoping this was contained to the dev environment.

**Comment by vladikoff** [comment]
Nothing actionable here afaik, we can revisit this if there are more gmail spam reports
