### ISSUE TITLE
support schema.org "confirm action" for account verification

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-auth-mailer#36]
Inspired by Ryan's link in #35, we could help GMail users out by supporting the schema.org confirm action. This would allow users to verify the account in one click from their GMail inbox.
https://developers.google.com/gmail/markup/reference/one-click-action#confirm_action

**Comment by shane-tomlinson** [comment]
This is an awesome idea.

**Comment by jrgm** [comment]
So Shane, do you want to take this?

**Comment by zaach** [comment]
We'd also have to register with Google: https://developers.google.com/gmail/markup/registering-with-google

**Comment by pdehaan** [comment]
Not sure if this is related or useful, but I thought this schema thing sounded familiar: https://github.com/mozilla/persona/pull/4057.

**Comment by rfk** [comment]
This might fit nicely under @eoger's general remit of "improve verification rate".

**Comment by rfk** [comment]
Great stuff here folks!   IIUC this will not be active until we do some registration with Google for our production servers, right?

@eoger, what metrics should we watch out for when this goes live?  I think it would make an interesting blog post or similar if we can say "increased verification by X%".

**Comment by vladikoff** [comment]
```javascript
query.one_click = true
var oneClickLink = this.verificationUrl + '?' + qs.stringify(query)
```
@rfk the one click link has an extra `one_click=true` parameter. I have no clue how we can extract the data and compare it with other clicks.

**Comment by rfk** [comment]
It would be neat to run this as an a/b test but probably too much mucking around to make it worthwhile.  I'm hoping it will show up as a measurable improvement in our verification rate, but we might need to try to limit it to "improved verification rate for gmail addresses" to make it visible.  I dunno, just thinking out loud mostly :-)
