### ISSUE TITLE
[l10n] slow progress on translation of 'Re-verify your account'

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-mailer#37]
This isn't a bug in fxa-auth-mailer per se, but maybe better to deal with this initially here.

I have a script to do some basic checks that l10n for auth-server email is happening correctly. To make it pass, it must afford for some locales that have not (yet) added translations for new strings. The strings for `'Re-verify your account'` have not been making progress for a couple of trains now, so just wanted to raise this topic, to see if there is something "stuck" in the way these localizations are done, or if fxa-auth-mailer is doing something wrong.

https://github.com/mozilla/fxa-auth-server/blob/master/scripts/e2e-email/localeQuirks.js#L36-L64

/cc @zaach, @stomlinson, @mathjazz

**Comment by mathjazz** [comment]
I see at least 26 languages (English included) with 'Re-verify your account' translated in Verbatim: 
https://localize.mozilla.org/projects/accounts

This is actually the number of locales at 100%, so even more might have the string translated.

**Comment by jrgm** [comment]
Thanks @mathjazz. 

So looking further, I can confirm that fxa-content-server-l10n does not have a translation of 'Re-verify your account' in the server.po file:
 ca
 en
 et
 eu
 ff
 fr
 he
 id
 ko
 lt
 pa
 pl
 rm
 sv
But that language is listed in the supported list https://github.com/mozilla/fxa-content-server/blob/master/server/config/production-locales.json. So, people are busy. 

However, in looking into things there *is* a configuration issue that would have prevented some of them (e.g., `uk`) from showing their translation, and I'll work on a fix to get that configured correctly.

**Comment by jrgm** [comment]
I'm closing this bug, since aside from the one config issue, there's nothing preventing this subject from being translated, so will just wait for it to happen in due course.
