### ISSUE TITLE
[train-39] `sl` Slovenian translations not being used - plural-forms change?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-mailer#43]
Not sure what is going on with this, but I've traced it back to this change of the Plural-Forms.

https://github.com/mozilla/fxa-content-server-l10n/commit/d0ac10ae189373497d58df2a7c8ffcb8c07972f8#diff-707c15e8ea20c1495a9fe8014942a382L13

With that change, email for signup is sent with 'Verify your account' and default English content body; if I use the previous form of `Plural-Forms`, the translation is used.

/cc @zaach, @mathjazz, @dannycoates

**Comment by mathjazz** [comment]
Slovenian (sl) switched from Verbatim to Pontoon, which seems to have different plural forms defined for the locale. Investigating, will report back.

**Comment by mathjazz** [comment]
Should be fixed as of https://github.com/mozilla/fxa-content-server-l10n/commit/90a7cd2884bbb87cae0e2cd96077aa7dc71cc248

**Comment by vladikoff** [comment]
Should be fixed for the deploy!
