### ISSUE TITLE
Support email change confirmation

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-auth-mailer#44]
Ref: https://github.com/mozilla/fxa-content-server/issues/2527

Here's the screen rfeeley proposes:
![screen shot 2015-06-10 at 3 15 07 pm](https://cloud.githubusercontent.com/assets/3903/8095517/b6aa4c42-0f83-11e5-94e3-6e95af46c9b1.png)

**Comment by shane-tomlinson** [comment]
Are we going to give the users the ability to add multiple email addresses? If not, the work "primary" is not necessary.

**Comment by pdehaan** [comment]
I like the mockup. I thought I vaguely recalled an idea to put the verification link under the button for other emails, but I can't find that in GitHub (or maybe I made that up). /cc @ryanfeeley @johngruen

**Comment by ryanfeeley** [comment]
Correct! @johngruen how is the email coming along? I should update my mockup to match what you have.

**Comment by pdehaan** [comment]
@ryanfeeley, wait, I'm correct, or @shane-tomlinson's comment is correct (re: "primary")?

In the unlikely chance that I'm correct, do you remember the bug number so I can link it here?

**Comment by ryanfeeley** [comment]
I don't see any harm in using the term 'primary" because I don't think it necessarily promises we are allowing additional emails (but when we do, our ass is covered).

**Comment by shane-tomlinson** [comment]
> I don't see any harm in using the term 'primary" because I don't think it necessarily promises we are allowing additional emails (but when we do, our ass is covered).

Can we just add `primary` when we have multiple addresses? :bike: :shed:

**Comment by ryanfeeley** [comment]
If it makes you feel better @shane-tomlinson. Also,better? ![confirm-change](https://cloud.githubusercontent.com/assets/68213/8117185/4d6ed92e-1054-11e5-8f5c-2b860a567c1d.png)

**Comment by vladikoff** [comment]
Closed per https://github.com/mozilla/fxa-content-server/issues/2527#issuecomment-184799470
