### ISSUE TITLE
Encourage users  to *change* their password rather than reset it?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#51]
It just occurred to me that in #26 we have wording like:

> if you didn't add a new device to your Firefox Account,
> you should change your password immediately at %(resetLink)s."

The wording says "change" but the link says "reset", and the side-effects are very different.  If the user does reset their password in response to this email, it will disconnect all their devices from sync and render their server-side sync data unrecoverable.  They will have to re-upload everything from scratch, which increases the change of getting them in a bad state with e.g. their bookmarks all messed up.

Perhaps we should link them to the "change password" page in this case?

(In future we can link to a dashboad where they can revoke the offending device without messing up the login state on any existing devices, which will be better than either option).

**Comment by ckarlof** [comment]
Agreed.

**Comment by TDA** [comment]
:+1: for this.

**Comment by rfk** [comment]
Fixed in https://github.com/mozilla/fxa-auth-mailer/pull/72
