### ISSUE TITLE
Change L10N section on readme.md

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-auth-mailer#52]
Apparently all of this is automated now.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/fxa-content-server-l10n/pull/50

**Comment by jrgm** [comment]
https://raw.githubusercontent.com/mozilla/fxa-content-server-l10n/master/scripts/extract_strings.sh

**Comment by rfk** [comment]
@eoger can you please update the docs here to be consistent with that improvements you made above?
