### ISSUE TITLE
[l10n][train-40] slow progress translating `Verify your Firefox Account`, etc. 

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-mailer#54]
This is a list of locales that have not yet translated the new strings `Verify your Firefox Account` and `Reset your Firefox Account password`. This is about half of the locales we support and will affect train-40 when it goes live.
```
 * ca
   cs
   cy
 * es-AR
   es-CL
   eu
 * ff
 * he
   hu
 * id
 * ko
 * lt
 * nb-NO
 * pa
 * pl
 * rm
   sk
   sq
   sr
   sv-SE
   tr
```
The ones marked with `*` have also not translated `Re-verify your account` from two months back (https://github.com/mozilla/fxa-auth-mailer/issues/37).

**Comment by jrgm** [comment]
Is it possible that translators are ignoring the `server.po` file, and just translating the `client.po`. 

/cc @zaach, @mathjazz, @shane-tomlinson

**Comment by mathjazz** [comment]
There are 19 locales at 100%, so I don't think they are skipping the file. Maybe we made more changes to server.po recently?

In any case, I suggest announcing new strings on the dev-l10n and dev-l10n-web mailing lists.

**Comment by rfk** [comment]
@mathjazz thanks for the tip!  Just to be clear, is [1] the sort of thing that would be welcome and expected from Firefox Accounts on these lists?

[1] https://groups.google.com/forum/#!topic/mozilla.dev.l10n/d-8DKabthvc

**Comment by mathjazz** [comment]
Yes, something like this would help every time we merge new strings in.

We have crucial information available on the [dashboard](https://l10n.mozilla-community.org/webdashboard/?locale=sl), but sending an email would bring it to localizers' attention. You could also add more information, like when is the deadline for localizers to catch the particular train.

**Comment by rfk** [comment]
I sent off an email to dev-l10-web, which seemed like the most appropriate forum.

For the future, we should include this as part of our l10n automation.  It looks like e.g. marketplace have a script to do this regularly:

  https://groups.google.com/forum/#!topic/mozilla.dev.l10n.web/Eq95L9ead_I

Personally it reads a little too robot -ike for my taste, but we could e.g. have a script to spit out a draft email that a human can look over and send to the list on each train cut.  @zaach thoughts?

**Comment by jrgm** [comment]
So there are a few more, now 22, at 100%. So that's an improvement. Will keep this open for now to continue to track.

**Comment by rfk** [comment]
FWIW we've now got semi-automated support for emailing the list with updates on each train.  @jrgm do you want to continue to keep it open as a reminder to revisit this?

**Comment by rfk** [comment]
> we've now got semi-automated support for emailing the list with updates

It's not clear to me whether this is actually happening when we cut the strings for each train; I don't see many messages when I search with:

  https://groups.google.com/forum/#!searchin/mozilla.dev.l10n.web/fxa

We may need to move to less "semi" automated for this script...

**Comment by vladikoff** [comment]
@vladikoff and @shane-tomlinson to chat about this

**Comment by vladikoff** [comment]
From talking to Shane:
Here are some action items that might work:

- We are going to disable locales that are below 70%
- We are going to revisit the locale translation % every quarter.  

To see % we have to look at this page https://localize.mozilla.org/projects/accounts/ and this page: https://pontoon.mozilla.org/projects/firefox-accounts/

I will follow up with a PR to disable the supported locales that are below 70%

**Comment by vladikoff** [comment]
from mtg: also check the mail script to include info about support / unsupported accounts

**Comment by vladikoff** [comment]
new locale list: 

"az",
"bg",
"cs",
"cy",
"da",
"de",
"dsb",
"en",
"en-GB",
"es",
"es-AR",
"es-CL",
"et",
"fa",
"ff",
"fr",
"fy",
"he",
"hi",
"hi-IN",
"hsb",
"hu",
"it",
"ja",
"kk",
"ko",
"lt",
"nl",
"pa",
"pl",
"pt",
"pt-BR",
"ro",
"rm",
"ru",
"sk",
"sl",
"sq",
"sr",
"sr-LATN",
"sv",
"sv-SE",
"tr",
"uk",
"zh-CN",
"zh-TW"

**Comment by vladikoff** [comment]
Updated: 

  'az',
  'bg',
  'cs',
  'cy',
  'da',
  'de',
  'dsb',
  'en',
  'en-GB',
  'es',
  'es-AR',
  'es-CL',
  'et',
  'fa',
  'ff',
  'fr',
  'fy',
  'he',
  'hi-IN',
  'hsb',
  'hu',
  'it',
  'ja',
  'kk',
  'ko',
  'lt',
  'nl',
  'pa',
  'pl',
  'pt',
  'pt-BR',
  'ro',
  'rm',
  'ru',
  'sk',
  'sl',
  'sq',
  'sr',
  'sr-LATN',
  'sv',
  'sv-SE',
  'tr',
  'uk',
  'zh-CN',
  'zh-TW'

**Comment by vladikoff** [comment]
Added pt-PT, see latest at https://github.com/mozilla/fxa-auth-server/blob/locale-update/config/supportedLanguages.js
