### ISSUE TITLE
Make all the emails look like the email format with the Firefox logo above

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#62]
I'm getting emails that don't look wonderful as the new email format. Please make them consistent. Unify?

**Comment by rfk** [comment]
see also #49

**Comment by ckarlof** [comment]
I'm closing #49, which is essentially a requirement how this bug should be implemented (i.e.. DRY).

**Comment by rfk** [comment]
Partially addressed in https://github.com/mozilla/fxa-auth-mailer/pull/72, although we haven't yet split out the HTML into a re-useable template so I'm leaving this broader issue open for now.
