### ISSUE TITLE
Sign our emails so we get snazzy authenticated "key" icons in gmail

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#64]
As described in:

 https://support.google.com/mail/answer/3070163

**Comment by pdehaan** [comment]
Odd that the Google support page wouldn't show an image of said "snazzy authenticated key", but this is what they seem to look like in my Gmail:
![inbox_-_peterdehaan_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/557895/8738679/b313030a-2be7-11e5-9356-0fdec532a895.png)

**Comment by brampitoyo** [comment]
This is what it looks like on Outlook.com:
![outlook-shield](https://cloud.githubusercontent.com/assets/51007/8739430/f1c7e568-2c8f-11e5-80a6-feabbb2cd613.PNG)

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/fxa-content-server/issues/1031

**Comment by vladikoff** [comment]
We need to verify with https://dmarcian.com/dmarc-inspector/

@jrgm is saying that we tried to do that last year and the dmarc inspector did not work out. There is some bug somewhere detailing that. 

@rfk what should we do?

**Comment by rfk** [comment]
@jrgm is this the bug you're thinking of?

  https://bugzilla.mozilla.org/show_bug.cgi?id=1003299

**Comment by jrgm** [comment]
Yeah, that's the one. Didn't (re-)digest it all.

**Comment by rfk** [comment]
Aye, there's a lot to take in from that bug.  I think we've got more pressing things to work on in our email and onboarding flow, so I suggest we backlog this for now and revisit it once we 're sure we've picked the next crop of low-hanging fruit around our verification emails.

(Although I will gladly accept an @ryanfeeley veto to say this *is* low-hanging fruit).

**Comment by rfk** [comment]
Also I think the above-linked bug is from before we switched to a shorter from-address on a different domain in https://github.com/mozilla/fxa-auth-server/issues/841.

**Comment by rfk** [comment]
In particular, it may be easier to start with #61 and get some sense of when and why we're not making it into the inbox.

**Comment by vladikoff** [comment]
@rfk @jrgm should we still keep looking into this? I am wondering why this is still a 'labs' only feature in gmail..

**Comment by rfk** [comment]
I don't think we need to move on it with any urgency, but I also kinda don't want to close the issue because it links to so much useful context.  Although ISTM it's almost entirely dependant on Ops bandwidth so maybe it's better tracked in bugzilla...

**Comment by ryanfeeley** [comment]
I think I'd asked about this a long time ago, and that it would require reaching out to Google, but if it's something we can get from our end, I'm all for it. Obviously, I can comment on engineering effort.

**Comment by seanmonstar** [comment]
Moved to https://github.com/mozilla/fxa-auth-server/issues/1855
