### ISSUE TITLE
Send verification reminder emails

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#65]
When a user leaves an account unverified, everyone loses. We should send out two different verification reminders, and optimize when the send them out.

First Reminder – The earliest I would recommend we sent this would be 24 hours (and change "A few days ago" to "Recently"). Compare that against 48 and 72 hours?
![reminder1](https://cloud.githubusercontent.com/assets/68213/8803458/08139346-2f95-11e5-9d49-b6c48ecf1981.png)

Second Reminder – The earliest I would recommend we sent this would be 5 days (and change "A few weeks ago" to "A while ago"). Compare that against 8 and 13 days?
![reminder2](https://cloud.githubusercontent.com/assets/68213/8803459/08151f86-2f95-11e5-983a-42e03956c052.png)

We would want to find the most responded to day for either reminder and then use that.

Notice anything?
![915px-fibonacci_spiral_34 svg](https://cloud.githubusercontent.com/assets/68213/8803618/cae67398-2f95-11e5-8b7e-24f2fe01ac4b.png)

**Comment by ryanfeeley** [comment]
@rfk Seems like low-effort high-impact based on the number of unverified accounts we have, no?

**Comment by rfk** [comment]
Yeah, I've been treading water on this one a bit because the journeybuilder folks also wanted to take a crack at it, but we should just bite the bullet and manage this ourselves.

**Comment by rfk** [comment]
@rfk to break out some sub-issues here

**Comment by ckarlof** [comment]
We might need to double check with legal about this one. Transactional emails are "ok" from a legal POV, and it's not clear whether an email reminder for a previously transactional email is still considered transactional.

**Comment by rfk** [comment]
I have vague recollections of getting a legal OK for this when the JourneyBuilder team was talking about doing it.  So I expect it will be OK, but we should definitely get confirmation.

**Comment by dannycoates** [comment]
Is it worth the extra translation overhead to have 2 distinct sets of copy for the first and second reminder?

**Comment by ckarlof** [comment]
For the record, I'm not warm on this one.

It's probably easy to do, but it also has the potential to annoy users if we do it badly. The upside is that it potentially gets us more accounts, but unfortunately only from users that weren't engaged enough to finish the process the begin with. 

At this point in time, I'd prefer to see us focus on communications that help deepen our relationship with users that have already signed up (e.g., on-boarding and early FxA experience) and de-prioritize ones that optimize account growth. We're getting all the ~~squandered opportunities~~ new signups we want from the first run flow in Fx40.

Sorry for the drive-by!  ¯\_(ツ)_/¯

**Comment by ryanfeeley** [comment]
@ckarlof I definitely don't want to annoy users, but if someone has gone through the trouble of creating an account, it's unilkely they will consciously want to leave it in an unverified state. I'm sure the vast majority of users simply didn't get around to click the link until the email was pushed down in their inbox. We could offer a delete account option and track that though.

**Comment by rfk** [comment]
I've also seen several instances of sporadic deliverability issues, where users show up to complain that the email didn't come through initially, but when they re-try to help debugging it comes through fine.  This could be a chance to re-connect with those users without them having to show up in bugzilla or IRC.

> We could offer a delete account option and track that though.

Done right, this could help provide some insight into the cause of our 20% verification failure rate.

> We're getting all the squandered opportunities new signups we want from the first run flow 

Good to keep ths in mind though :-)

**Comment by rfk** [comment]
Emails added in https://github.com/mozilla/fxa-auth-mailer/pull/72; @dannycoates can you please migrate this issue to fxa-auth-server for implementing the actually-send-them part?

**Comment by vladikoff** [comment]
this will become a feature card....

**Comment by rfk** [comment]
It is so: https://mozilla.aha.io/features/FXA-57

**Comment by vladikoff** [comment]
@rfk some notes from mtg, did I forget anything?:

-> this email should hook into activity events so we can check retention and see if this email is useful
-> make this an experiment (does this mean we should need 'enrolled' vs 'sent' events) ?

Personal note: focus this email on the Sync experience (explain sync more)

**Comment by rfk** [comment]
> focus this email on the Sync experience

This was a really strong take-away for me as well.  The email currently says "a few days ago you created a Firefox Account", but perhaps we should be talking specifically about the thing the user was trying to do, e.g. "a few days ago you started connecting your device to Firefox Sync, but didn't complete it".

**Comment by shane-tomlinson** [comment]
> The email currently says "a few days ago you created a Firefox Account", but perhaps we should be talking specifically about the thing the user was trying to do, e.g. "a few days ago you started connecting your device to Firefox Sync, but didn't complete it".

Since FxA is a gateway for users to perform an action on another service, mentioning the service makes a lot of sense. I think the email should still mention Firefox Accounts, otherwise a user could be confused that the email says "Firefox Sync" or "Pocket" and the link opens "Firefox Accounts".

**Comment by rfk** [comment]
Agreed, we still need to mention the account.  But this also affects how we would measure success of this feature - if we drive more verified accounts, but those users don't actually end up connected to sync after verification, we've failed them.
