### ISSUE TITLE
Send a post-verification welcome email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#66]
To increase multiple device sync engagement, we should send users a welcome email that contains a sign-in link that, like our manage link, will sign them into their account (pre-fill the username field, or better, the cached page). We should measure the effectiveness of this email in terms of it increasing multi-device engagement.
![post-verification](https://cloud.githubusercontent.com/assets/68213/8805270/51858dd2-2f9e-11e5-84c8-9e012c8142d2.png)

**Comment by rfk** [comment]
> We should measure the effectiveness of this email in terms of it increasing
> multi-device engagement.

We'll soon have explicit metrics on this front, so let's consider more precisely how we'll measure effectiveness of this.  Is it enough to say "after we started doing this, the rate of new multi-device connections per day increased from X to Y" or do you want to run a more formal able-driven experiment?

**Comment by rfk** [comment]
> send users a welcome email that contains a sign-in link that [...] will sign them into their account

Hmmm...I assume we want this link to result in them being signed in to sync on their device.   Do we have the necessary magic in place to make that work on Android or iOS?  I know that https://www.mozilla.org/firefox/sync/ is capable of doing this on desktop by launching into about:accounts, but it doesn't seem to have the same capability on Android.

We may have to block on some or all of https://github.com/mozilla/fxa/issues/48 before we can implement this as described.

Or, we could ship an initial version that just links to https://www.mozilla.org/firefox/sync/ and then iterate on making things more automatic from there.

**Comment by rfk** [comment]
@ryanfeeley we can try to ship an initial version of this on the coming train, but we'll need your input on precisely how to scope it.  Open questions:

* We don't have device names yet; can you re-word the "you successfully connected" part to avoid them for now?
* Where should all of the links go?
* What if the account was created when signing up for e.g. Pocket rather than sync?  Should we send a different email, the same, or no email at all?
* Does it make sense for us to send both this email, *and* the proposed JourneyBuilder emails from the engagement team?

**Comment by ryanfeeley** [comment]
* RE: device names: You have successfully connected your first Firefox to your account.

* RE: Where should links go:
LINK (UTM parameters pendings)
* Android:
https://www.mozilla.org/firefox/android/?utm_source=firefox-browser&utm_medium=referral&utm_campaign=fxa-post-verification-email

* iOS: (the page will be live by Sept 1st, 2015 and it have a coming soon sign
up)
https://www.mozilla.org/firefox/ios/?utm_source=firefox-browser&utm_medium=referral&utm_campaign=fxa-post-verification-email

Alternatively  (UTM parameters pendings):
https://www.mozilla.org/firefox/?utm_source=firefox-browser&utm_medium=referral&utm_campaign=fxa-post-verification-email

Mozilla support (same as original email)

* We should definitely be sending these for sync users. Let's discuss other cases.

* I'll review JourneyBuilder.

**Comment by chrismore** [comment]
We may want to use utm_medium=email here since these are specifically links in an email to the mobile product pages. I am asking Gareth to see what he thinks.

**Comment by garethcull** [comment]
Since the inbound traffic from those links originates from an email, we should set utm_medium=email. We should also change utm_source since traffic from the link isn't originating from the browser.

Let's use:
?utm_source=email&utm_medium=email&utm_campaign=fxa-post-verification-email

Thanks.

**Comment by rfk** [comment]
> I'll review JourneyBuilder.

Chatting with @vladikoff, he suggested that we might take this off of the current train in favour of pushing through the JourneyBuilder work, which will do much the same job for users who've opted in to the marketing email.  Once we've more experience with that, we can re-consider sending this email to all users.

(The difference here is that we can send a single "welcome" email to *all* users, while the JourneyBuilder stuff will only be available to users who've opted in to marketing emails)

@rfeeley thoughts?  I'll leave the final call on staging this relative JourneyBuilder up to you.

**Comment by rfk** [comment]
Fixed in https://github.com/mozilla/fxa-auth-mailer/pull/72

**Comment by ryanfeeley** [comment]
@rfk I'm noticing this email sends for non-Sync users as well, which is not a good idea. Thoughts?

**Comment by rfk** [comment]
Hmm, indeed that seems less than ideal.  Might be a bit of work to fix but we should definitely look into it.  Tracking in https://github.com/mozilla/fxa-auth-mailer/issues/129
