### ISSUE TITLE
Scan email translations for bad links

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-mailer#67]
We need to check the source of our translations for emails and make sure they are scanned for bad strings the same way. 

there seems to be some server.pot content for emails in the content server, but are there other template files?

cc @TDA

**Comment by vladikoff** [comment]
```
[18:50:47]  <jrgm>	vladikoff: https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/fr/LC_MESSAGES/server.po#L214-L222
[18:51:30]  <vladikoff>	jrgm, that does not exist in https://github.com/mozilla/fxa-content-server/blob/master/locale/templates/LC_MESSAGES/server.pot so the template is from somewhere else
```

**Comment by vladikoff** [comment]
@TDA we MIGHT need to convert your xss task into a plugin and use it in both repos.

**Comment by TDA** [comment]
@vladikoff ok, do we know which files are to be scanned/parsed?

**Comment by vladikoff** [comment]
@zaach any idea where these come from:
```
#: templates/new_sync_device.html:2 templates/new_sync_device.txt:1
msgid "Account activity notice"
msgstr "Informations sur l'activité du compte"

#: templates/new_sync_device.html:3 templates/new_sync_device.txt:2
msgid ""
"A new device is now syncing with all of the devices connected to your "
"Firefox Account."
msgstr ""
"Un nouvel appareil se synchronise désormais avec tous les autres appareils "
"connectés à votre compte Firefox."

```

**Comment by shane-tomlinson** [comment]
@vladikoff - that is a new template in the fxa-auth-mailer repo - https://github.com/mozilla/fxa-auth-mailer/blob/master/templates/new_sync_device.html

**Comment by vladikoff** [comment]
@shane-tomlinson in the content server we have a file like this https://github.com/mozilla/fxa-content-server/blob/master/locale/templates/LC_MESSAGES/server.pot that has nothing about `new_sync_device`. is there another .pot file for stuff like `new_sync_device` email templates or am I misunderstanding how it works?

**Comment by shane-tomlinson** [comment]
From IRC:
> [15:23:25]  <stomlinson>	vladikoff: the templates extracted to the fxa-content-server-l10n repo, where the translators do their updates. We then import the changes back into the fxa-content-server repo. It looks like the content server versions have not been updated in a while. :/
[15:24:27]  <stomlinson>	vladikoff: at least that's how I thought the process worked.
[15:26:11]  <stomlinson>	vladikoff: maybe we should make that part of the `version` grunt-task, pull in the l10n repo, merge the changes, commit, then do the rest.

**Comment by vladikoff** [comment]
Should @TDA's script scan https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/en/LC_MESSAGES/server.po instead? Hoping the `en` local can be used as source of truth. It must be only updated by us.

**Comment by zaach** [comment]
The templates in the l10n repo are considered canonical– any reason not to use those? They're pulled in to `app/bower_components/fxa-content-server-l10n/locale/templates/LC_MESSAGES/`.

**Comment by vladikoff** [comment]
> The templates in the l10n repo are considered canonical– any reason not to use those? They're pulled in to app/bower_components/fxa-content-server-l10n/locale/templates/LC_MESSAGES/.

Thanks Zach! 

@TDA if the "full" templates live in the l10n repo then we should probably move those XSS parse tasks out of the content server, any issues with that?

**Comment by TDA** [comment]
@vladikoff sounds reasonable to me, but wouldnt we need to run these tests even if the o/p of the l10n repo was clean? Just to be sure nothing was added?

**Comment by vladikoff** [comment]
> but wouldnt we need to run these tests even if the o/p of the l10n repo was clean? Just to be sure nothing was added?

Sorry, could you explain / rephrase your concern?

**Comment by TDA** [comment]
@vladikoff So, when we run the tests only on the l10n repo, wont we still need to run it once on the content-server? or is that redundant?

**Comment by pdehaan** [comment]
> @vladikoff: Hoping the en local can be used as source of truth. It must be only updated by us.

Should we use the `en` locale, or just the [locale/templates/LC_MESSAGES/*.pot](https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/templates/LC_MESSAGES/server.pot) files?

**Comment by vladikoff** [comment]
@pdehaan after asking @zaach, it seems we should be using `/locale/templates/LC_MESSAGES` and  **not** the `en` locale

**Comment by rfk** [comment]
IIUC this can be closed now that we finally landed the l10n linter; @shane-tomlinson please confirm and close if so

**Comment by shane-tomlinson** [comment]
Closing!
