### ISSUE TITLE
Remove styles and link from verify email translation?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-mailer#68]
Per [/templates/verify.html:55](https://github.com/mozilla/fxa-auth-mailer/blob/6aac195ff6d1692b239c7906fd1becd95ee85ebf/templates/verify.html#L55), we have the following string:

```
{{{t "For more information, please visit <a href='https://support.mozilla.org' style='color: #0095dd; text-decoration: none;'>Mozilla Support</a>"}}}
```

Not sure if we want to change the `href` URL to `%(supportLink)s` and the inline styles to `%(supportStyles)s` to make it harder for things to get altered or typoed.

**Comment by shane-tomlinson** [comment]
> Not sure if we want to change the href URL to %(supportLink) and the inline styles to %(supportStyles) to make it harder for things to get altered or typoed.

I think this is a fantastic idea, if we can do it easily.

**Comment by pdehaan** [comment]
@shane-tomlinson We do it already for some templates, for example, [templates/new_sync_device.html:57](https://github.com/mozilla/fxa-auth-mailer/blob/6aac195ff6d1692b239c7906fd1becd95ee85ebf/templates/new_sync_device.html#L57):

```
... immediately at <a href='%(resetLink)s'>%(resetLink)s</a>."}}}
```

In fact, here's my poor attempt at greppin' all `href=` tags that aren't parameterized:
```
➜  fxa-auth-mailer git:(master) grep -irn ' href=' templates
```

| FILE | STRING |
|----|----|
templates/new_sync_device.html:58: | `{{{t "For more information, please visit <a href='https://support.mozilla.org'>Mozilla Support</a>"}}}`
templates/password_changed.html:58: | `{{{t "For more information, please visit <a href='https://support.mozilla.org'>Mozilla Support</a>"}}}`
templates/password_reset.html:58: | `{{{t "For more information, please visit <a href='https://support.mozilla.org'>Mozilla Support</a>"}}}`
templates/reset.html:93: | `{{{t "For more information, please visit <a href='https://support.mozilla.org'>Mozilla Support</a>"}}}`
templates/unlock.html:91: | `{{{t "For more information, please visit <a href='https://support.mozilla.org'>Mozilla Support</a>"}}}`
templates/verify.html:55: | `{{{t "For more information, please visit <a href='https://support.mozilla.org' style='color: #0095dd; text-decoration: none;'>Mozilla Support</a>"}}}</p>`
```

**Comment by rfk** [comment]
Fixed in https://github.com/mozilla/fxa-auth-mailer/pull/72
