### ISSUE TITLE
Prepare train-45 email string changes for translation

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#69]
We have a suite of email refactorings lined up for train-45:

* #51 
* #60 
* #62 
* #65
* #68 

And maybe #66, although it has some open questions associated with it.

Many of these will require new of modified strings, so in order to give translators as much time as possible, let's try to land the strings first.  Following the pattern used by content-server, we can:

* make any trivial string changes directly in the existing templates
* put new strings that don't have a home yet in a `templates/strings.txt` where they can be found by the string-extraction script

We can then worry about the HTML, refactoring etc later on in the cycle.

@dannycoates can you please make this the first action on the email-quality bugs, to go through and find all the new strings and ensure they're captured appropriately?

**Comment by vladikoff** [comment]
> @dannycoates can you please make this the first action on the email-quality bugs, to go through and find all the new strings and ensure they're captured appropriately?

@dannycoates there is this page that we can use for strings: http://people.mozilla.org/~rfeeley/fxa-emails/ with draft designs (ignore the "Two Factor Authentication Enabled"). @ryanfeeley is updating the links and finishing up the designs.

We should worry about translation strings that include links, hopefully we can fix this up as part of https://github.com/mozilla/fxa-auth-mailer/issues/68

**Comment by dannycoates** [comment]
@vladikoff see https://github.com/mozilla/fxa-auth-mailer/commit/ff774b9569f7143ec65991efcad6b441229e020a

**Comment by vladikoff** [comment]
@dannycoates do we need "Sign in to Sync" / "Connect another device" + "Still there?" ? 

cc @ryanfeeley

**Comment by dannycoates** [comment]
@vladikoff chill, dude :snowman:

**Comment by dannycoates** [comment]
@ryanfeeley don't "activate" and "verify" mean the same thing in this context? Why are we using both?

**Comment by ryanfeeley** [comment]
@dannycoates Not a strongly-held opinion, but I have found that confirmation mails use words like confirm, activate and verify interchangeably. It's a bit of a vocabulary shotgun blast approach I guess. It is intentional.
