### ISSUE TITLE
po2json@0.3.0 installs 70mb of nodejs 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-mailer#70]
![image](https://cloud.githubusercontent.com/assets/128755/9502203/e5712882-4bfd-11e5-8512-99a0e1d9ba56.png)

I'm not clear where this is coming from but it seems like updating to po2json@0.4.0 fixes that

**Comment by dannycoates** [comment]
I feel lighter already :+1:

**Comment by vladikoff** [comment]
Thanks Danny!!!
