### ISSUE TITLE
Stretched "activate now" button when verification email viewed in Outlook

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#73]
I was investigating our new mozsvc email-on-acid account, and sent a test verification email.  The really long "resume" token seemed to cause problems with line-breaking and resulted in a very wide "activate now" button in some desktop clients:

![screen shot 2015-08-28 at 15 10 45](https://cloud.githubusercontent.com/assets/34695/9539599/fe56134a-4d96-11e5-8993-6dcf8f5fef4f.png)

Similar artifacts showed up in a couple of other clients as well:

![screen shot 2015-08-28 at 15 12 28](https://cloud.githubusercontent.com/assets/34695/9539617/49ae0c80-4d97-11e5-8ef5-a8761a6f1876.png)

@ryanfeeley thoughts?

(I can also give you direct access to the test results, just ping me on IRC and I'll get you the account creds)

**Comment by shane-tomlinson** [comment]
@dannycoates - are you taking care of this bug this train?

**Comment by rfk** [comment]
Assigning this to @ryanfeeley for additiona commentary/triage.  One simple fix here might be to ensure our resume-tokens contain line-splittable characters by e.g. inserting some "." characters and ignoring them at parse time.  But that's a pretty gross hack...

**Comment by ryanfeeley** [comment]
A cursory search turned up some proprietary IE code:

`<p style="word-break:break-all;">`
`    <font style="word-break:break-all;">hxxp://really_long_link</font>`
`</p>`

but also turned up the question, why can't our links be shorter?

**Comment by rfk** [comment]
Thanks @ryanfeeley!

> why can't our links be shorter?

I'd like them to be, but there's a *lot* of information in the resume token these days.  Filed https://github.com/mozilla/fxa-content-server/issues/3026 to discuss options in that regard.
