### ISSUE TITLE
x-link sent with "New sign-in to Sync" has pathname of 'undefined'

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-mailer#75]
I was running current fxa-auth-server with master with updated shrinkwrap to pick up last fxa-auth-mailer, and the tests pending in https://github.com/mozilla/fxa-auth-server/pull/1050, and it noted that the `X-Link` email header was now returning `undefined?email=foo%40example.com` instead of `/v1/reset_password?email=foo%40example.com`.

https://github.com/mozilla/fxa-auth-mailer/commit/e9a06ced3576b0c846826d23e675ed6de27d80d0#diff-3427c5e3d78d8d6550178ad46b9e0680L231

**Comment by dannycoates** [comment]
master auth-mailer needs https://github.com/mozilla/fxa-auth-server/pull/1034 to work correctly

**Comment by rfk** [comment]
IIUC this is fixed as of the above PR, closing
