### ISSUE TITLE
New subject 'New sign-in to Sync' should include 'Firefox Accounts' for better context

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-mailer#76]
https://github.com/mozilla/fxa-auth-mailer/commit/e9a06ced3576b0c846826d23e675ed6de27d80d0#diff-3427c5e3d78d8d6550178ad46b9e0680L240

A user looking at their Inbox seeing 'New sign-in to Sync' would have no idea whether that is relevant to them without the word 'Firefox' to provide context.

**Comment by dannycoates** [comment]
ISTM that the "From" field adds enough context

**Comment by dannycoates** [comment]
@ryanfeeley ?

**Comment by ryanfeeley** [comment]
That was the assumption, and that a longer subject line might push the full subject out of view on some email clients, e.g. mobile.

**Comment by ckarlof** [comment]
How about: "Firefox Sync: New Sign-in"

**Comment by billmaggs** [comment]
New Sign in to Firefox

**Comment by rfk** [comment]
> New Sign-in to Firefox

This got @ryanfeeley approval in product meeting today, although I think we should keep capitalization of "sign-in" consistent with the existing string.  Let's make it so.

**Comment by ryanfeeley** [comment]
Agreed @rfk!

**Comment by vladikoff** [comment]
Final string name will be:

# 'New sign-in to Firefox'

@ryanfeeley let me know if that is wrong

**Comment by billmaggs** [comment]
Looks right to me.

**Comment by ryanfeeley** [comment]
LGTM.
