### ISSUE TITLE
Improve all the emails in all browsers and make look the same with logo

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#77]
Windows users are having a rough experience with our emails, and they are not alone.

We need simple bullet proof email that looks like this in all browsers:

http://people.mozilla.org/~rfeeley/fxa-emails/

**Comment by vladikoff** [comment]
@rfk could you email @ryanfeeley and @vladikoff email on acid creds so we can test out a new template? Thanks!

**Comment by rfk** [comment]
creds sent; we're also going to reach out to the engagement team for help on this

**Comment by rfk** [comment]
It's not clear what concrete actions remain on this bug.  @ryanfeeley the outlook duplicate-content issue should be fixed by #89, which also introduces templating to help ensure the emails look the same.  What else needs fixing to "improve all the emails in all browsers"?

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-auth-mailer/pull/89
