### ISSUE TITLE
Link to a specific sumo article instead of the sumo root.

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-auth-mailer#79]
The fine print in the emails say "For more information, please visit <a href="https://support.mozilla.org/">Mozilla Support</a>". If a user is sufficiently confused/concerned that they click on the link, they are likely to be disappointed/frustrated at being taken to a very general site where they will probably struggle to find the information they are looking for.

I think it would be more helpful to create a sumo page with general information and advice about emails sent by FxA and include a link to that.

**Comment by shane-tomlinson** [comment]
@rfk to find out who to talk to about getting some SUMO articles.

**Comment by rfk** [comment]
AFAICT the person I was thinking of is Joni Savage:

  https://phonebook.mozilla.org/#search/Joni%20Savage

**Comment by rfk** [comment]
Also I think we *can* create such a page ourselves, but working with someone like Joni will likely produce a better result.

**Comment by jonisavage** [comment]
Thanks, Vlad, for looping me in. 

We can definitely get SUMO articles ready for you. Here are the existing Sync articles, but if you need new ones for specific use cases, we can do that too. Feel free to let me know here or "need info" me on any bugs.

1. Sync on desktop: https://support.mozilla.org/en-US/products/firefox/sync-your-browsers
2. Sync on Android: https://support.mozilla.org/en-US/products/mobile/save-share-and-sync-firefox-android/sync
3. Sync on iOS: https://support.mozilla.org/en-US/kb/bookmarks-wont-sync-firefox-ios and https://support.mozilla.org/en-US/kb/sync-your-firefox-browsing-history-ios

**Comment by vladikoff** [comment]
@jonisavage ,

To keep it simple for now we could make a "Firefox Accounts" section and have  a category or section for "emails" or "received emails"

Here's a quick draft of emails we have right now:

===============

#####  new_sync_device.html - A device began syncing with the devices connected to your Firefox Account.

This means ....

#####  password_changed.html - Your Firefox Account password has been successfully changed.

This means you recently reset your password, no further action is required. 

#####  password_reset.html - "Your Firefox Account password has been successfully reset."

< content>

#####  post_verify.html - "You successfully connected your first device to your Firefox Account."

< content> 	

#####  unlock.html - "For security reasons your Firefox Account was put on lockdown. To perform account-level activities, please click the link to re-verify your account now."

This can happen if .....
	
#####   verification_reminder.html - Recently you created a Firefox Account, but never verified it. Please activate your account by confirming this email address.

Someone created an account with your email address. If it was you then please confirm your email.

#####  verify.html - Please activate your account by confirming this email address.

Someone created an account with your email address. If it was you then please confirm your email.

==============

And then we can link out to Sync sections, such as Sync for Desktop, iOS and Android.

If this is on the right track then I can help fill out the needed content ....

cc @rfk

**Comment by rfk** [comment]
Note we also have this more FxA-specific article already:

  https://support.mozilla.org/en-US/kb/access-mozilla-services-firefox-accounts

**Comment by rfk** [comment]
I like the general form being suggested here, a landing page for people who think "I got an email from Firefox Accounts. What does it mean?  What should I do?"

**Comment by jonisavage** [comment]
Creating content and a category for Firefox Accounts will be simple on our side. I'd like to check with the Brand/Marketing people though to make sure we're aligned. We have a Sync marketing page (https://www.mozilla.org/en-US/firefox/sync/) but not a Firefox Accounts page (not that I know of), so I want to make sure that won't be a problem. The reason we hadn't added a category yet was because we weren't promoting FxA yet, but that was almost a couple of years ago. 

We can start writing the articles though, regardless. We also have an article on how to verify your account (https://support.mozilla.org/en-US/kb/im-having-problems-confirming-my-firefox-account), and I'll take a look at the rest of the drafts on Vlad's list.

**Comment by rfk** [comment]
> The reason we hadn't added a category yet was because we weren't promoting FxA yet,

I think that's still true, we don't need to promote FxA as a standalone product, because it doesn't really let you do anything by itself.  It's only useful to you if you're connecting to some service like sync.

**Comment by vladikoff** [comment]
@jonisavage @rfk how about create a page that lives on: 

https://support.mozilla.org/en-US/kb/im-having-problems-with-my-firefox-account
#### Title: I'm having problems with my Firefox Account

^ and we link to that in our emails.

For now that page can link to:

* https://support.mozilla.org/en-US/kb/im-having-problems-confirming-my-firefox-account
* Sync on desktop: https://support.mozilla.org/en-US/products/firefox/sync-your-browsers
* Sync on Android: https://support.mozilla.org/en-US/products/mobile/save-share-and-sync-firefox-android/sync
* Sync on iOS: https://support.mozilla.org/en-US/kb/bookmarks-wont-sync-firefox-ios and https://support.mozilla.org/en-US/kb/sync-your-firefox-browsing-history-ios

and we can add more content to that later?

**Comment by rfk** [comment]
@vladikoff SGTM

**Comment by vladikoff** [comment]
todo: create a bugzilla bug for this

**Comment by vladikoff** [comment]
We also have this page, not sure if it is linked anywhere 

https://support.mozilla.org/en-US/kb/access-mozilla-services-firefox-accounts?redirectlocale=en-US&redirectslug=how-set-and-use-firefox-accounts-mozilla-services

**Comment by vladikoff** [comment]
bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1216605

**Comment by vladikoff** [comment]
We are working in this Google doc to populate the contents of the new support page: https://docs.google.com/document/d/1uz--PZRuaTbirA_KoPphpuo0d1cv_Z6GBxEGcJx-LcY/edit

**Comment by vladikoff** [comment]
@jonisavage will take some time to add more email content tomorrow

**Comment by vladikoff** [comment]
@jonisavage I added a few sentences for every possible email, feel free to change anything in that doc that I wrote. Let me know if you need any additional details for that page. Otherwise we are ready to start linking to https://support.mozilla.org/kb/im-having-problems-with-my-firefox-account when possible.

**Comment by vladikoff** [comment]
@shane-tomlinson @ryanfeeley first version of the page is live here : https://support.mozilla.org/en-US/kb/im-having-problems-with-my-firefox-account

any suggestions / edits?

**Comment by mhammond** [comment]
LGTM, but note that the section "You successfully connected your first device to your Firefox Account." should probably s/first device/a device/ (and similarly in the body) as an email is sent whenever *any* device connects.

**Comment by rfk** [comment]
> an email is sent whenever any device connects.

FWIW, we no longer send those as of train-48, because they were freaking too many people out.

**Comment by vladikoff** [comment]
Just to clarify we have 2 templates:

1. Post verification - First device https://github.com/mozilla/fxa-auth-mailer/blob/93b0f3100482130d2f7e874c4d72124e6493198b/partials/post_verify.html

and the deactivated one 

2. new sync device https://github.com/mozilla/fxa-auth-mailer/blob/master/templates/new_sync_device.html

The one in the support article is the post verification one

**Comment by rfk** [comment]
Should this now come out of "blocked" if that article is live?

**Comment by vladikoff** [comment]
Will need to check with the L10N schedule and then we will know when to merge the change for the support link

**Comment by vladikoff** [comment]
@jonisavage Thanks again for your help on this, is 3 weeks enough time to get that page translated?

**Comment by vladikoff** [comment]
> @jonisavage Thanks again for your help on this, is 3 weeks enough time to get that page translated?

If yes, then we can merge the https://github.com/mozilla/fxa-auth-mailer/pull/98 PR right after we cut the train next week

**Comment by shane-tomlinson** [comment]
> FWIW, we no longer send those as of train-48, because they were freaking too many people out.

Google sends them. I thought Facebook did too. The intention is to cause people to cause a mini-freak out if an unrecognized device connects, isn't it?

**Comment by jonisavage** [comment]
@vladikoff Yes, 3 weeks is perfect. I'll send it off to our L10N community next week then.
