### ISSUE TITLE
Run our template through emailonacid optimizer

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#83]
Email on acid provide an "optimizer" that can find problems with HTML email:

  http://www.emailonacid.com/app/optimizehtml/

We should run our template through it and follow its suggestions.  This might help with some of the display jank in outlook.

**Comment by rfk** [comment]
@vladikoff was this part of the cleanup in #89?

**Comment by vladikoff** [comment]
Yeap!

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-auth-mailer/pull/89
