### ISSUE TITLE
Duplicate content is display in some outook variants

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#84]
More outlook display jank:

![screen shot 2015-09-21 at 16 48 16](https://cloud.githubusercontent.com/assets/34695/10008164/9a9c3bfc-6080-11e5-977c-9af5efa7e089.png)

Sounds like we may be hitting the same problem as: http://stackoverflow.com/questions/9116135/duplicate-content-in-html-email-outlook-2007#9126257

**Comment by dannycoates** [comment]
From that stackoverflow comment

> Since outlook uses word to render emails, it has the concept of page breaks. If you have an image spanning a page break then funny things start to happen, such as duplication or big gaps. The only solution I know is to re-arrange the content, so that images don't lie on the page break areas.

:scream: FML

**Comment by vladikoff** [comment]
<img src=http://www.365ninja.com/wp-content/uploads/clippy.png width=100 align=right />

**Comment by rfk** [comment]
IIUC this is fixed by #89

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-auth-mailer/pull/89
