### ISSUE TITLE
Alt tag for Firefox logo in the email should be "Firefox logo"

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#86]
Low priority, but easy to do, the alt tag for Firefox logo in the email should be "Firefox logo" and not just "Firefox". Seeing a lot of "Firefox" in user testing when people check their webmail and images aren't loading.

**Comment by vladikoff** [comment]
from mtg: remove text from the alt tag because it is not adding anything useful

**Comment by ryanfeeley** [comment]
@vladikoff OK, spoke with accessibility team. You are right that in this context "Firefox Logo" is not necessary, although they did say to make sure to include alt="" so users will the image was defined as decorative.

**Comment by shane-tomlinson** [comment]
> so users will the image was defined as decorative.

I did not know that was a best practice, thank you for the info.
