### ISSUE TITLE
Finalize design of improved "account activity" email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#88]
Our account activity notification is a little spare on information. What can we reliably know that we can include so that the user knows they are the ones signing in.

* We can definitely repeat the account email.
* The sign-in time?
* Platform?
* Country?

What's available today that can we can make use of.

**Comment by ryanfeeley** [comment]
Looking at device activity in my Google account, they can (at a minimum) present:

* Current device (true/false)
* Device platform (e.g. Mac)
* Device name (e.g. rfeeleys-Mac, none)
* Browsers (e.g. Firefox 44.0, Chrome 46.0)
* Browser location (e.g. Toronto, ON Canada)
* Browser activity time (e.g. Yesterday, 12:39)
* Last location used (e.g. Toronto, ON, Canada, just now)
* Device model (e.g. iPhone)
* Last synced (e.g. Today at 10:10 – 3 hours ago)

Other providers:
* Dropbox includes IP address
* Apple includes device verified (true/false)
* Apple includes refresh devices button

Would ours truly be devices or just profiles?

**Comment by rfk** [comment]
@dannycoates I recalled some IRC chatter that you were looking into this, so I took the liberty of assigning it to you for further triage.

> Would ours truly be devices or just profiles?

We don't currently have this distinction, two profiles running on the same machine would appear to FxA as two separate devices.  But if we need to design for something different in order to provide a great user experience, it's better to know now that later...

**Comment by rfk** [comment]
@ryanfeeley I'm taking the liberty of morphing this into a more outcome-oriented bug to "finalize design of improved 'account activity' email".  We don't have to limit ourselves to what's available today, let's decide what information we want and it can feed into the details of the device registration API.

**Comment by vladikoff** [comment]
@ryanfeeley and @dannycoates to chat about this...

**Comment by rfk** [comment]
@dannycoates @ryanfeeley did you come up with any proposed changes to the activity-event email at this stage, or should we focus on the devices view and put this on the backburner for a future iteration?

**Comment by vladikoff** [comment]
todo: remove from milestone

**Comment by rfk** [comment]
We'll revisit this as a separate feature card, not part of the initial device-registration work

**Comment by vladikoff** [comment]
from mtg:  @rfk what do we do with this issue?

**Comment by rfk** [comment]
We're doing this work in new features/issues, I don't see any particularly valuable context here to copy over; closing
