### ISSUE TITLE
Blocky email fonts in outlook 2013 and later

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#90]
Behold:
![screen shot 2015-09-30 at 16 02 17](https://cloud.githubusercontent.com/assets/34695/10185553/ace02b08-678c-11e5-92ec-90681f70ad79.png)

Email-on-acid test case: https://www.emailonacid.com/app/acidtest/display/result/N9ui2lkD4g9cvmFz1L1eYKFEXxuVlKZTCjHB49qGCQWi3/38/

**Comment by rfk** [comment]
Although it's not clear to me whether this is an artifact of email-on-acid, e.g. their "gmail firefox windows" render also shows a less-than-stellar font:
![screen shot 2015-09-30 at 16 55 51](https://cloud.githubusercontent.com/assets/34695/10186415/30cda9de-6794-11e5-92bd-9bc1ae54c0f3.png)

But when I open up one of our emails in gmail in firefox on my windows box, it looks nice.

**Comment by vladikoff** [comment]
I think this is just how it renders in email-on-acid, seems like they have some font smoothing disabled on the system level

**Comment by rfk** [comment]
Yeah, since we're unable to repro this on any physical machines, let's close it out until we have more evidence that it's a problem.
