### ISSUE TITLE
Get email formatting advice from DEG

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-mailer#91]
Filing a fresh bug to track getting DEG's input on our email templates. @edmoz has volunteered to coordinate with Brent from DEG.

The most important email is our "verify your account" email, the template for which can be found here:

  https://github.com/mozilla/fxa-auth-mailer/blob/master/templates/verify.html

Any modifications suggested to that one, we can easily apply to all the others.  Should I generate a snapshot of this with the values filled in?

A recent run-through in email-on-acid revealed ugly fonts on various platforms, including Outlook 2013 and above (https://github.com/mozilla/fxa-auth-mailer/issues/90).  But I'm sure there are other display problems lurking, and any advice on how to find or fix them would be awesome.

**Comment by edmoz** [comment]
I'll send this to DEG today

**Comment by vladikoff** [comment]
Closing for now, unless we need more feedback.....
