### ISSUE TITLE
factor template links out into some common set of attributes 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-mailer#94]
https://github.com/mozilla/fxa-auth-mailer/pull/93#discussion_r41954491

**Comment by vladikoff** [comment]
Also add a test for change password

https://github.com/mozilla/fxa-auth-mailer/pull/93#discussion_r42151811

**Comment by vladikoff** [comment]
Also check https://github.com/mozilla/fxa-auth-mailer/pull/93#discussion_r42152154

**Comment by vladikoff** [comment]
Changing this to a "good first bug", the changes in this bug do not change any email behaviour.

**Comment by shane-tomlinson** [comment]
@vbudhram did this in https://github.com/mozilla/fxa-auth-mailer/pull/190, closing.
