### ISSUE TITLE
FXA-57: Finalize "Reminder to Verify" email content

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-mailer#95]
This issue is the tracking discussion about the contents of the "reminder to verify email"
Earlier discussion here: https://github.com/mozilla/fxa-auth-mailer/issues/65#issuecomment-145674183

cc @ryanfeeley 

Need to FXA-57 milestone when available...

**Comment by rfk** [comment]
> Need to FXA-57 milestone when available...

If you want to go ahead and create one, the procedure for this (which I should document but haven't) is:

* Add the milestone by hand on the mozilla/fxa repo
* Run [1] to propagate it to the other repos

[1] https://github.com/mozilla/fxa/blob/master/scripts/sync_milestones.js

**Comment by vladikoff** [comment]
> If you want to go ahead and create one,

Done! Thanks for the pointer
