### ISSUE TITLE
Add support for sending "Reminder to Verify" emails

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-mailer#99]
Related to https://github.com/mozilla/fxa-auth-server/issues/1081

**Comment by vladikoff** [comment]
Need to talk to @rfk about "Checking account verification status"....
might use the read-only replica of the DB.

**Comment by rfk** [comment]
> might use the read-only replica of the DB.

This seems fine if the replication delay is small enough, but let's be clear about what benefit we hope to get from using it.

**Comment by vladikoff** [comment]
todo: rm sqs
